const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),{spawn}=require('node:child_process');
const {createAccess}=require('../server/simplehmi/access'),express=require('../server/node_modules/express'),WS=require('../server/node_modules/ws');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<100;i++){const r=await fn();if(r)return r;await delay(100)}throw Error('timed out')}
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'flex-access-'));let clock=Date.now();const access=createAccess({dir,now:()=>clock});const app=express();app.use(express.json());app.use(access.middleware);access.mount(app);app.get('/project',(req,res)=>res.json({ok:true}));const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s))});t.after(()=>{server.close();fs.rmSync(dir,{recursive:true,force:true})});const url='http://127.0.0.1:'+server.address().port;const request=async(route,body,headers={})=>{const r=await fetch(url+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}};return {access,dir,url,request,advance:ms=>clock+=ms};}
test('protected access stores only hashes, rejects anonymous and forged owner requests, and honors expiry/revocation',async t=>{
 const f=await fixture(t),password='test-owner-password-only';assert.equal((await f.request('/project')).status,200);const enabled=await f.request('/access/enable',{password});assert.equal(enabled.status,200);const headers={Cookie:enabled.cookie};assert.equal((await f.request('/project')).status,401);const hostileHost=await new Promise((resolve,reject)=>{require('node:http').get(f.url+'/project',{headers:{Host:'example.invalid'}},r=>{r.resume();resolve(r.statusCode)}).on('error',reject)});assert.equal(hostileHost,403);
 const issued=await f.request('/access/tokens',{label:'只读测试',scope:'read',days:1},headers);assert.equal(issued.status,200);const auth={Authorization:'Bearer '+issued.data.token};assert.equal((await f.request('/project',undefined,auth)).status,200);assert.equal((await f.request('/access/tokens',{},auth)).status,403);assert.equal((await f.request('/agent/plans',{},auth)).status,403);assert.equal((await f.request('/project',undefined,{...headers,Authorization:'Bearer '+'a'.repeat(43)})).status,401);
 const disk=fs.readFileSync(path.join(f.dir,'access/policy.json'),'utf8');assert.ok(!disk.includes(password)&&!disk.includes(issued.data.token));const list=await f.request('/access/tokens',undefined,headers);assert.ok(!JSON.stringify(list.data).includes('hash'));const identity=f.access.identify({headers:{authorization:auth.Authorization}});assert.equal(f.access.current(identity),true);f.advance(86400001);assert.equal(f.access.current(identity),false);assert.equal((await f.request('/project',undefined,auth)).status,401);
 const relogin=await f.request('/access/login',{password});assert.equal(relogin.status,200);const key=(await f.request('/access/tokens',{label:'控制测试',scope:'full',days:7},{Cookie:relogin.cookie})).data;await f.request('/access/tokens/'+key.id+'/revoke',{}, {Cookie:relogin.cookie});assert.equal((await f.request('/project',undefined,{Authorization:'Bearer '+key.token})).status,401);
 const changed=await f.request('/access/password',{currentPassword:password,password:'new-test-owner-password'},{Cookie:relogin.cookie});assert.equal(changed.status,200);assert.equal((await f.request('/project',undefined,{Cookie:relogin.cookie})).status,401);assert.equal((await f.request('/project',undefined,{Cookie:changed.cookie})).status,200);assert.equal((await f.request('/access/login',{password})).status,401);
 const restart=createAccess({dir:f.dir});assert.throws(()=>restart.identify({headers:{cookie:relogin.cookie}}),e=>e.status===401);assert.equal(restart.enabled(),true);
});
test('server capability checks cannot be bypassed using client scope, direct save, legacy write or physical-write flags',async t=>{
 const f=await fixture(t),enabled=await f.request('/access/enable',{password:'test-owner-password-only'}),headers={Cookie:enabled.cookie};
 for(const scope of ['read','engineering','full']){const key=(await f.request('/access/tokens',{label:scope,scope,days:30},headers)).data;const identity=f.access.identify({headers:{authorization:'Bearer '+key.token}});assert.doesNotThrow(()=>f.access.authorize(identity,'GET','/agent/state'));for(const route of ['/project','/load/id','/write','/access/tokens','/ai/config'])assert.throws(()=>f.access.authorize(identity,'POST',route,{}),e=>e.status===403);if(scope==='read')assert.throws(()=>f.access.authorize(identity,'POST','/agent/plans',{}),e=>e.status===403);else assert.doesNotThrow(()=>f.access.authorize(identity,'POST','/agent/plans',{}));if(scope==='full'){assert.doesNotThrow(()=>f.access.authorize(identity,'POST','/control/arm',{}));assert.throws(()=>f.access.authorize(identity,'POST','/control/arm',{allowPhysical:true}),e=>e.status===403);}else assert.throws(()=>f.access.authorize(identity,'POST','/control/pause',{}),e=>e.status===403);}
 for(let i=0;i<5;i++)assert.equal((await f.request('/access/login',{password:'wrong'})).status,401);assert.equal((await f.request('/access/login',{password:'wrong'})).status,429);
});
function socket(origin,headers={}){const ws=new WS(origin.replace('http','ws')+'/socket.io/?EIO=4&transport=websocket',{headers});const ready=new Promise((resolve,reject)=>{ws.on('error',reject);ws.on('message',raw=>{const s=raw.toString();if(s.startsWith('0'))ws.send('40');else if(s==='2')ws.send('3');else if(s.startsWith('40'))resolve(true);else if(s.startsWith('44'))resolve(false)})});return {ws,ready}}
test('real FUXA enforces token roles, gates upstream HTTP and sockets, and revoked control returns to manual',{timeout:30000},async t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'flex-access-real-')),root=path.resolve(__dirname,'..');const port=await new Promise(r=>{const s=net.createServer().listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})});let backend,log='',sockets=[];t.after(async()=>{for(const s of sockets)s.close();if(backend&&backend.exitCode===null)await new Promise(r=>{backend.once('exit',r);backend.kill('SIGTERM');setTimeout(()=>{backend.kill('SIGKILL');r()},2500).unref()});fs.rmSync(temp,{recursive:true,force:true})});
 const origin='http://127.0.0.1:'+port,request=async(route,body,headers={})=>{const r=await fetch(origin+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}};const api=(route,body,headers)=>request('/simplehmi/api'+route,body,headers);
 backend=spawn(process.execPath,[path.join(root,'server/main.js')],{cwd:temp,env:{...process.env,SIMPLEHMI:'1',PORT:String(port),userDir:temp},stdio:['ignore','pipe','pipe']});backend.stdout.on('data',d=>log+=d);backend.stderr.on('data',d=>log+=d);await until(async()=>{try{return (await api('/status')).data.ready}catch{return false}});
 const existing=socket(origin);sockets.push(existing.ws);assert.equal(await existing.ready,true);const closed=new Promise(r=>existing.ws.once('close',r));const enabled=await api('/access/enable',{password:'test-owner-password-only'}),owner={Cookie:enabled.cookie};assert.equal(enabled.status,200,enabled.data.error);await closed;
 assert.equal((await api('/project')).status,401);assert.equal((await request('/api/project')).status,401);assert.equal((await request('/api/project',undefined,owner)).status,200);
 const key=(await api('/access/tokens',{label:'真实适配验收',scope:'full',days:7},owner)).data,auth={Authorization:'Bearer '+key.token};assert.equal((await api('/agent/state',undefined,auth)).status,200);const cli=await require('node:util').promisify(require('node:child_process').execFile)(process.execPath,[path.join(root,'scripts/agent-cli.cjs'),'capabilities'],{env:{...process.env,SIMPLEHMI_URL:origin+'/simplehmi/api/',FLEXHMI_TOKEN:key.token}});assert.equal(JSON.parse(cli.stdout).authorization.scope,'full');assert.ok(!cli.stdout.includes(key.token));assert.equal((await request('/api/project',undefined,auth)).status,403);const rejected=socket(origin,auth);sockets.push(rejected.ws);assert.equal(await rejected.ready,false);const accepted=socket(origin,owner);sockets.push(accepted.ws);assert.equal(await accepted.ready,true);
 const {waterDemo}=await import('../simplehmi/water-demo.mjs');await api('/project',waterDemo('intelligent-control','access_control'),owner);await until(async()=> (await api('/values',undefined,auth)).data.values.pump_command?.quality==='good');const state=(await api('/agent/state',undefined,auth)).data;assert.equal((await api('/control/arm',{expectedRevision:state.revision,allowPhysical:true},auth)).status,403);assert.equal((await api('/control/arm',{expectedRevision:state.revision},auth)).status,200);await api('/access/tokens/'+key.id+'/revoke',{},owner);await until(async()=> (await api('/control/status',undefined,owner)).data.state==='manual');assert.equal((await api('/control/status',undefined,auth)).status,401);assert.equal((await api('/control/status')).status,401);assert.ok(!log.includes(key.token));
});
