const {test}=require('node:test'),assert=require('node:assert/strict');
const {applyOperations,digest}=require('../server/simplehmi/agent');
const {validate}=require('../server/simplehmi');
function project(){return {schemaVersion:1,id:'agent_test',name:'Agent test',devices:[{id:'plc',name:'模拟PLC',protocol:'sim',host:'127.0.0.1',port:502,unitId:1,polling:1000,timeout:2000,tags:[{id:'level',name:'水位',address:1,type:'UInt16',memory:'400000',divisor:1,initial:50,writable:false}]}],activePageId:'main',pages:[{id:'main',name:'总览',width:1200,height:800,components:[{id:'tank',kind:'tank',label:'水箱',x:48,y:64,w:160,h:160,tagId:'level'},{id:'pump',kind:'pump',label:'水泵',x:500,y:64,w:160,h:160,valueTag:'level',details:[{tag:'level',label:'水位'}]}],connections:[{id:'supply',from:'tank',to:'pump',tagId:'level'}]}]}}
test('agent deletion repairs all dependent bindings and reports runtime impact',async()=>{const before=project(),hash=digest(before),r=await applyOperations(before,{operations:[{op:'device.delete',id:'plc'}]},validate);assert.equal(digest(before),hash);assert.equal(r.project.devices.length,0);assert.ok(!r.project.pages[0].components[0].tagId);assert.ok(!r.project.pages[0].components[1].valueTag);assert.deepEqual(r.project.pages[0].components[1].details,[]);assert.ok(!r.project.pages[0].connections[0].tagId);assert.equal(r.impacts.filter(x=>x.code==='binding-cleared').length,3);assert.ok(r.impacts.some(x=>x.code==='runtime-restart'));});
test('component deletion cascades connections; invalid plans never mutate input',async()=>{const before=project(),r=await applyOperations(before,{operations:[{op:'component.delete',pageId:'main',id:'pump'}]},validate);assert.deepEqual(r.project.pages[0].connections,[]);assert.ok(r.impacts.some(x=>x.code==='connection-removed'));await assert.rejects(()=>applyOperations(before,{operations:[{op:'page.delete',id:'main'}]},validate),/至少/);assert.equal(before.pages.length,1);});
test('topological layout respects lock and leaves no overlapping nodes',async()=>{const p=project();p.pages[0].components.push({id:'label',kind:'text',label:'工艺标题',x:32,y:16,w:600,h:40,locked:true});const r=await applyOperations(p,{operations:[{op:'project.optimize'}]},validate),page=r.project.pages[0];assert.equal(page.components[2].x,32);assert.equal(page.components[2].y,16);assert.ok(page.components[0].x+160<page.components[1].x);assert.equal(r.blocked,false);assert.ok(page.connections[0].points.length>=2)});
test('orthogonal routing avoids obstacle and follows moved endpoints',async()=>{const {routePage,segmentBlocked}=await import('../simplehmi/topology.mjs');const p=project().pages[0];p.components.push({id:'obstacle',kind:'text',x:280,y:80,w:130,h:130});let r=routePage(p);assert.deepEqual(r.diagnostics,[]);let pts=r.page.connections[0].points;for(let i=1;i<pts.length;i++){assert.ok(pts[i].x===pts[i-1].x||pts[i].y===pts[i-1].y);assert.equal(segmentBlocked(pts[i-1],pts[i],[{x:280,y:80,r:410,b:210}]),false)}p.components[1].y=350;r=routePage(p);assert.equal(r.page.connections[0].points.at(-1).y,423.862);});
test('unroutable ports produce a blocking diagnostic, not fake straight lines',async()=>{const {routePage}=await import('../simplehmi/topology.mjs'),p=project().pages[0];p.components[1].x=150;const r=routePage(p);assert.equal(r.page.connections[0].routeStatus,'blocked');assert.deepEqual(r.page.connections[0].points,[]);assert.equal(r.diagnostics[0].code,'route-blocked')});
test('mode validation distinguishes available configuration from future execution',async()=>{const p=project(),r=await applyOperations(p,{operations:[{op:'project.configure',mode:'industry-ai'}]},validate);assert.equal(r.project.system.mode,'industry-ai');assert.ok(r.impacts.some(x=>x.code==='industry-review-required'));assert.throws(()=>validate({...p,system:{mode:'unsupported'}}),/模式/);assert.throws(()=>validate({...p,pages:[{...p.pages[0],connections:[{id:'edge',from:'tank',to:'missing'}]}]}),/端点/)});
module.exports={project};

test('different equipment sizes align their visible ports with no gratuitous elbow',async()=>{const {optimizePage}=await import('../simplehmi/topology.mjs');const p=project().pages[0];p.components[0].h=200;p.components[1].h=160;const r=optimizePage(p),e=r.page.connections[0];assert.equal(e.routeStatus,'ok');assert.equal(e.points.length,2);assert.equal(e.points[0].y,e.points[1].y);assert.equal(e.routeInfo.bends,0);assert.equal(e.routeInfo.arrowDirection,'right');assert.ok(e.points[0].x<r.page.components[0].x+r.page.components[0].w,'port is on visible tank, not selection box');});
test('reversed and vertical flows point toward destination with the appropriate side',async()=>{const {routePage}=await import('../simplehmi/topology.mjs');let p=project().pages[0];p.connections[0].from='pump';p.connections[0].to='tank';let e=routePage(p).page.connections[0];assert.equal(e.routeStatus,'ok');assert.deepEqual(e.resolvedPorts,{from:'left',to:'right'});assert.equal(e.routeInfo.arrowDirection,'left');p=project().pages[0];p.components[1].x=48;p.components[1].y=450;e=routePage(p).page.connections[0];assert.equal(e.routeStatus,'ok');assert.deepEqual(e.resolvedPorts,{from:'bottom',to:'top'});assert.equal(e.routeInfo.arrowDirection,'bottom');});
test('offset horizontal ports use a centered corridor instead of tiny end stubs',async()=>{const {routePage}=await import('../simplehmi/topology.mjs'),p=project().pages[0];p.components[1].y=320;const e=routePage(p).page.connections[0];assert.equal(e.routeStatus,'ok');assert.equal(e.points.length,4);assert.equal(e.routeInfo.bends,2);assert.equal(e.points[1].x,e.points[2].x);assert.ok(e.points[1].x>p.components[0].x+p.components[0].w+30);assert.ok(e.points[1].x<p.components[1].x-30);assert.equal(e.routeInfo.arrowDirection,'right');});
test('manual flow drawings cannot silently disconnect during automatic layout',async()=>{const {optimizePage}=await import('../simplehmi/topology.mjs'),p=project().pages[0];p.components.push({id:'legacy',kind:'flow',x:0,y:0,w:1200,h:800});assert.throws(()=>optimizePage(p),/手绘管线/)});
test('process optimization preserves unconnected titles, controls and cards while aligning equipment',async()=>{
 const {waterDemo}=await import('../simplehmi/water-demo.mjs'),{optimizePage}=await import('../simplehmi/topology.mjs');
 const before=waterDemo('visualization','layoutdemo').pages[0],connected=new Set(before.connections.flatMap(e=>[e.from,e.to])),result=optimizePage(before);
 for(const c of before.components.filter(c=>!connected.has(c.id)))assert.deepEqual(result.page.components.find(n=>n.id===c.id),c);
 assert.deepEqual(result.diagnostics,[]);assert.ok(result.page.connections.every(e=>e.points.length===2));
 const second=optimizePage(result.page);assert.deepEqual(second.page,result.page,'optimizing an already optimized process is stable');
});
