const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createAssessmentStore}=require('../server/simplehmi/assessment-store');
test('assessment archive survives restart, searches and pages without leaking full observations into lists',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'flex-assessments-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const store=createAssessmentStore(dir),assessment={conclusion:'总水量满足演示条件',capturedAt:1,expiresAt:2,citations:[{title:'供水演示资料',source:'测试样例'}],conditions:[],observed:{sample:{value:123}}};
 const ids=[];
 for(let i=0;i<25;i++)ids.push(store.save({project:{id:'water',name:'供水工程'},expectedRevision:'revision',source:i%2?'model':'external',summary:'供水评估 '+i,assessment}).id);
 store.save({project:{id:'other',name:'其他工程'},source:'external',summary:'其他报告',assessment});
 const restarted=createAssessmentStore(dir),first=restarted.list({projectId:'water',limit:20});
 assert.equal(first.records.length,20);assert.ok(first.nextCursor);
 const last=restarted.list({projectId:'water',limit:20,cursor:first.nextCursor});
 assert.equal(last.records.length,5);assert.equal(last.nextCursor,null);
 assert.equal(new Set([...first.records,...last.records].map(r=>r.id)).size,25);
 assert.equal(first.records[0].assessment,undefined);assert.equal(first.records[0].expired,true);
 assert.deepEqual(restarted.read(ids[0]).assessment.observed,{sample:{value:123}});
 assert.equal(restarted.list({projectId:'water',source:'model',q:'总水量'}).records.length,12);
 assert.equal(restarted.list({projectId:'other',q:'供水演示资料'}).records.length,1);
 assert.equal(restarted.list({q:'不存在'}).records.length,0);
 for(const query of [{limit:0},{limit:101},{projectId:'../file'},{source:'invalid'},{cursor:ids[0],projectId:'other'},{q:'x'.repeat(501)}])assert.throws(()=>restarted.list(query));
 assert.throws(()=>restarted.read('../config'));
 assert.throws(()=>restarted.read('evaluation_missing'),e=>e.status===404);
 const legacy=restarted.read(ids[0]);delete legacy.projectId;delete legacy.projectName;delete legacy.source;
 fs.writeFileSync(path.join(dir,'assessments',legacy.id+'.json'),JSON.stringify(legacy));
 fs.writeFileSync(path.join(dir,'assessments','evaluation_broken.json'),'{');
 fs.writeFileSync(path.join(dir,'assessments','context_ignore.json'),'{}');
 const listed=restarted.list({limit:100});
 assert.equal(listed.records.length,26);assert.equal(listed.unreadable.length,1);
 const old=listed.records.find(r=>r.id===legacy.id);assert.equal(old.projectId,null);assert.match(old.projectName,/工程未记录/);
 assert.equal(restarted.list({projectId:'water',limit:100}).records.length,24);
 assert.throws(()=>restarted.read('evaluation_broken'),/无法读取/);
});
