const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {validateControl,createControl}=require('../server/simplehmi/control');const {applyOperations}=require('../server/simplehmi/agent');const {validate}=require('../server/simplehmi');
function project(){return {schemaVersion:1,id:'control_test',name:'控制验收',system:{mode:'intelligent-control'},devices:[{id:'plc',name:'模拟',protocol:'sim',host:'127.0.0.1',port:502,unitId:1,polling:1000,timeout:2000,tags:[{id:'level',name:'水位',address:1,memory:'400000',type:'Float32',divisor:1,sim:'manual',writable:false},{id:'pump',name:'泵',address:2,memory:'0',type:'Bool',divisor:1,sim:'manual',writable:true},{id:'permit',name:'允许',address:3,memory:'0',type:'Bool',divisor:1,sim:'manual',writable:false}]}],pages:[{id:'page',width:1280,height:720,components:[]}],control:{rules:[{id:'rule',name:'低位启动',enabled:true,inputTag:'level',outputTag:'pump',direction:'low',onThreshold:30,offThreshold:70,onValue:1,offValue:0,outputMin:0,outputMax:1,holdMs:1000,minIntervalMs:2000,maxAgeMs:3500,guards:[{tagId:'permit',op:'eq',value:1}]}]}}}
function fixture(t,{physical=false,write}={}){let p=project(),time=10000;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hmi-control-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));if(physical)p.devices[0].protocol='ModbusTCP';const values={level:{value:20,quality:'good',ts:time},pump:{value:0,quality:'good',ts:time},permit:{value:1,quality:'good',ts:time}},writes=[];
 const control=createControl({getProject:()=>p,readValues:()=>values,now:()=>time,dir,writeValue:async(id,value)=>{writes.push({id,value});if(write)return write(id,value);values[id].value=value;values[id].ts=time;return {verified:true,value}}});
 return {control,values,writes,p,advance:ms=>{time+=ms;for(const v of Object.values(values))v.ts=time},setProject:next=>{p=next}};}
test('hysteresis, stable duration and minimum interval prevent chattering',async t=>{const f=fixture(t);f.control.arm();await f.control.tick();assert.equal(f.writes.length,0);f.advance(1000);await f.control.tick();assert.deepEqual(f.writes,[{id:'pump',value:1}]);f.values.level.value=50;f.advance(500);await f.control.tick();assert.equal(f.writes.length,1);f.values.level.value=80;await f.control.tick();f.advance(500);await f.control.tick();assert.equal(f.writes.length,1);f.advance(1100);await f.control.tick();assert.deepEqual(f.writes.at(-1),{id:'pump',value:0});assert.equal(f.control.status().rules[0].writes,2)});
test('fresh false permissive requests off; stale data faults without inventing a safe output',async t=>{const f=fixture(t);f.p.control.rules[0].holdMs=0;f.control.arm();await f.control.tick();f.advance(2100);f.values.permit.value=0;await f.control.tick();assert.equal(f.writes.at(-1).value,0);f.values.level.quality='stale';await f.control.tick();assert.equal(f.control.status().state,'fault');assert.equal(f.writes.length,2);f.values.level.quality='good';await f.control.tick();assert.equal(f.writes.length,2)});
test('manual takeover persists and restarting or configuration changes never auto-arm',async t=>{const f=fixture(t);assert.equal(f.control.status().state,'manual');f.control.arm();f.control.takeover('pump');assert.equal(f.control.status().state,'manual');f.advance(3000);await f.control.tick();assert.equal(f.writes.length,0);f.control.arm();f.p.control.rules[0].onThreshold=25;await f.control.tick();assert.equal(f.control.status().state,'manual');assert.equal(f.writes.length,0)});
test('external output changes and unverified writes fault rather than being silently overwritten',async t=>{const f=fixture(t);f.control.arm();f.values.pump.value=1;await f.control.tick();assert.equal(f.control.status().state,'fault');assert.equal(f.writes.length,0);const g=fixture(t,{write:async()=>({verified:false})});g.p.control.rules[0].holdMs=0;g.control.arm();await g.control.tick();assert.equal(g.control.status().state,'fault');await g.control.tick();assert.equal(g.writes.length,1)});
test('physical output requires exact session scope and data readiness',t=>{const f=fixture(t,{physical:true});assert.throws(()=>f.control.arm(),/授权/);assert.throws(()=>f.control.arm({allowPhysical:'false',physicalTargets:['pump']}),/授权/);assert.throws(()=>f.control.arm({allowPhysical:true,physicalTargets:['other']}),/授权/);f.values.level.ts=1;assert.throws(()=>f.control.arm({allowPhysical:true,physicalTargets:['pump']}),/过期/);f.advance(0);assert.equal(f.control.arm({allowPhysical:true,physicalTargets:['pump']}).state,'automatic')});
test('validation rejects inverted thresholds, shared output and unauthorized tag types',()=>{let p=project();p.control.rules[0].offThreshold=20;assert.throws(()=>validateControl(p),/回差/);p=project();p.control.rules.push({...p.control.rules[0],id:'other'});assert.throws(()=>validateControl(p),/同时/);p=project();p.devices[0].tags[1].writable=false;assert.throws(()=>validateControl(p),/写入/);p=project();p.control.rules[0].onValue=2;assert.throws(()=>validateControl(p),/范围/);p=project();p.devices[0].tags[1].type='Float32';p.control.rules[0].onValue=1e300;p.control.rules[0].outputMax=1e300;assert.throws(()=>validateControl(p),/范围/)});
test('deleting control dependencies disables the rule with a visible impact instead of leaving a live dangling action',async()=>{const p=project();const result=await applyOperations(p,{operations:[{op:'tag.delete',deviceId:'plc',id:'level'}]},validate);assert.equal(result.project.control.rules[0].enabled,false);assert.match(result.project.control.rules[0].invalidReason,/level/);assert.ok(result.impacts.some(i=>i.code==='rule-disabled'));assert.equal(p.control.rules[0].enabled,true)});
test('takeover during an in-flight write prevents subsequent rules from writing',async t=>{let release;const f=fixture(t,{write:()=>new Promise(r=>release=r)});f.p.control.rules[0].holdMs=0;f.p.devices[0].tags.push({...f.p.devices[0].tags[1],id:'pump2'});f.values.pump2={...f.values.pump};f.p.control.rules.push({...f.p.control.rules[0],id:'rule2',outputTag:'pump2'});f.control.arm();const running=f.control.tick();assert.equal(f.writes.length,1);f.control.pause();release({verified:true,value:1});await running;assert.equal(f.control.status().state,'manual');assert.equal(f.control.status().rules[0].writes,0);assert.ok(f.control.events().some(e=>e.event==='write-verified'));});
module.exports={project};
