const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createControl,validateControl}=require('../server/simplehmi/control'),{applyOperations}=require('../server/simplehmi/agent'),{validate}=require('../server/simplehmi');
function project(){return {schemaVersion:1,id:'sequence',name:'步骤测试',system:{mode:'intelligent-control'},devices:[{id:'device',name:'模拟',protocol:'sim',host:'127.0.0.1',port:502,unitId:1,polling:500,timeout:2000,tags:[{id:'level',name:'液位',address:1,memory:'400000',type:'Float32',divisor:1,sim:'manual',initial:20},{id:'pump',name:'泵',address:2,memory:'0',type:'Bool',divisor:1,sim:'manual',initial:0,writable:true},{id:'permit',name:'允许',address:3,memory:'0',type:'Bool',divisor:1,sim:'manual',initial:1}]}],pages:[{id:'page',name:'流程',width:800,height:600,components:[]}],control:{rules:[],machines:[{id:'machine',name:'供水步骤',enabled:true,initialState:'idle',maxAgeMs:3500,minIntervalMs:1000,guards:[{tagId:'permit',op:'eq',value:1}],states:[{id:'idle',name:'待机',timeoutMs:0,actions:[{tagId:'pump',value:0,min:0,max:1}],transitions:[{to:'supply',priority:0,afterMs:1000,holdMs:500,conditions:[{tagId:'level',op:'lt',value:30}]}]},{id:'supply',name:'供水',timeoutMs:10000,actions:[{tagId:'pump',value:1,min:0,max:1}],transitions:[{to:'done',priority:0,afterMs:0,holdMs:0,conditions:[{tagId:'level',op:'gte',value:70}]}]},{id:'done',name:'完成',timeoutMs:0,actions:[{tagId:'pump',value:0,min:0,max:1}],transitions:[]}]}]}}}
function fixture(t,{p=project(),write}={}){let time=10000;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'flex-sequence-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const values=Object.fromEntries(p.devices.flatMap(d=>d.tags).map(t=>[t.id,{value:t.initial??0,quality:'good',ts:time}])),writes=[];
 const control=createControl({getProject:()=>p,readValues:()=>values,now:()=>time,dir,writeValue:async(id,value)=>{writes.push({id,value});if(write)return write(id,value,values);values[id]={value,ts:time,quality:'good'};return {verified:true,value}}});return {control,values,writes,p,m:p.control.machines[0],advance:ms=>{time+=ms;for(const v of Object.values(values))v.ts=time}};}
async function start(f){f.control.arm();f.advance(1000);await f.control.tick();f.advance(500);await f.control.tick()}
test('sequence waits for dwell/stable conditions, verifies outputs, completes and monitors its terminal state',async t=>{const f=fixture(t);f.control.arm();await f.control.tick();assert.equal(f.writes.length,0);f.advance(1000);await f.control.tick();assert.equal(f.writes.length,0);f.advance(500);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'supply');assert.equal(f.values.pump.value,1);f.values.level.value=80;await f.control.tick();assert.equal(f.writes.length,1);f.advance(1000);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'done');assert.equal(f.values.pump.value,0);f.advance(1000);await f.control.tick();assert.equal(f.writes.length,2);assert.match(f.control.status().machines[0].lastMessage,/终点/);assert.equal(f.control.events().filter(e=>e.event==='transition-completed').length,2)});
test('conditions must remain stable and priority explicitly chooses among matching branches',async t=>{const f=fixture(t);f.m.states[0].transitions.push({to:'done',priority:1,afterMs:1000,holdMs:0,conditions:[{tagId:'level',op:'gt',value:0}]});f.control.arm();f.advance(1000);await f.control.tick();f.values.level.value=35;f.advance(200);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'done');assert.equal(f.writes.length,0);assert.equal(f.control.status().machines[0].transitions,1)});
for(const failure of ['stale','external','timeout','guard'])test('sequence '+failure+' faults without forcing an invented safe value',async t=>{const f=fixture(t);await start(f);assert.equal(f.values.pump.value,1);if(failure==='stale')f.values.level.quality='stale';if(failure==='external')f.values.pump.value=0;if(failure==='timeout')f.advance(10000);if(failure==='guard')f.values.permit.value=0;await f.control.tick();assert.equal(f.control.status().state,'fault');assert.equal(f.writes.length,1);await f.control.tick();assert.equal(f.writes.length,1)});
test('a fresh controller requires explicit arming and initial outputs; exact physical scope includes every machine target',t=>{const p=project();p.devices[0].protocol='ModbusTCP';const f=fixture(t,{p});assert.equal(f.control.status().state,'manual');assert.throws(()=>f.control.arm(),/授权/);assert.throws(()=>f.control.arm({allowPhysical:true,physicalTargets:['pump','other']}),/授权/);f.values.pump.value=1;assert.throws(()=>f.control.arm({allowPhysical:true,physicalTargets:['pump']}),/起始步骤/);f.values.pump.value=0;assert.equal(f.control.arm({allowPhysical:true,physicalTargets:['pump']}).state,'automatic');f.control.takeover('pump');assert.equal(f.control.status().state,'manual')});
function twoOutputs(){const p=project();p.devices[0].tags.push({...p.devices[0].tags[1],id:'pump2'});for(const s of p.control.machines[0].states)s.actions.push({...s.actions[0],tagId:'pump2'});return p}
test('a later action failure leaves prior verified writes recorded, does not advance state and never rolls back outputs',async t=>{const f=fixture(t,{p:twoOutputs(),write:async(id,value,values)=>{if(id==='pump2')throw Error('disconnected');values[id].value=value;return {verified:true,value}}});await start(f);assert.equal(f.control.status().state,'fault');assert.equal(f.values.pump.value,1);assert.equal(f.values.pump2.value,0);assert.equal(f.control.status().machines[0].stateId,'idle');assert.equal(f.control.status().machines[0].writes,1);assert.match(f.control.status().reason,/已有 1 项/);assert.equal(f.control.events().filter(e=>e.event==='transition-completed').length,0)});
test('takeover during an in-flight step prevents later actions',async t=>{let release;const f=fixture(t,{p:twoOutputs(),write:()=>new Promise(r=>release=r)});f.control.arm();f.advance(1000);await f.control.tick();f.advance(500);const pending=f.control.tick();assert.equal(f.writes.length,1);f.control.pause();release({verified:true,value:1});await pending;assert.equal(f.control.status().state,'manual');assert.equal(f.writes.length,1);assert.ok(f.control.events().some(e=>e.event==='write-verified'));assert.ok(!f.control.events().some(e=>e.event==='transition-completed'))});
test('Float32 readback accepts representable quantization but detects a different register value',async t=>{const p=project();p.devices[0].tags[1].type='Float32';p.devices[0].tags[1].memory='400000';p.control.machines[0].states[1].actions[0]={tagId:'pump',value:0.1,min:0,max:1};const f=fixture(t,{p,write:async(id,value,values)=>{values[id].value=Math.fround(value);return {verified:true,value:values[id].value}}});await start(f);await f.control.tick();assert.equal(f.control.status().state,'automatic');f.values.pump.value=Math.fround(0.10001);await f.control.tick();assert.equal(f.control.status().state,'fault')});
test('validation rejects unreachable graphs, ambiguous priorities, missing action vectors, duplicate controllers and out-of-range writes',()=>{let p=project();p.control.machines[0].states.push({id:'unreachable',name:'不可达',timeoutMs:0,actions:[{tagId:'pump',value:0,min:0,max:1}],transitions:[]});assert.throws(()=>validateControl(p),/无法/);p=project();p.control.machines[0].states[0].transitions.push({...p.control.machines[0].states[0].transitions[0]});assert.throws(()=>validateControl(p),/优先级/);p=twoOutputs();p.control.machines[0].states[1].actions.pop();assert.throws(()=>validateControl(p),/全部输出/);p=project();p.control.machines.push({...structuredClone(p.control.machines[0]),id:'second'});assert.throws(()=>validateControl(p),/同时控制/);p=project();p.control.machines[0].states[1].actions[0].value=2;assert.throws(()=>validateControl(p),/范围/);p=project();p.control.machines[0].states[0].transitions[0].conditions=[];p.control.machines[0].states[0].transitions[0].afterMs=0;assert.throws(()=>validateControl(p),/延时/)});
test('Agent point deletion and changed knowledge disable dependent machines with visible impact',async()=>{const p=project(),r=await applyOperations(p,{operations:[{op:'tag.delete',deviceId:'device',id:'level'}]},validate);assert.equal(r.project.control.machines[0].enabled,false);assert.ok(r.impacts.some(i=>i.code==='machine-disabled'));const entry={id:'e',title:'依据',domain:'测试',source:'fixture',version:1,content:'用于流程测试的示例条件'};p.knowledge=[entry];p.control.machines[0].evidence=[{entryId:'e',version:1}];const k=await applyOperations(p,{operations:[{op:'knowledge.upsert',entry:{...entry,version:2}}]},validate);assert.equal(k.project.control.machines[0].enabled,false);assert.match(k.project.control.machines[0].invalidReason,/更新/)});
module.exports={project};
test('an output used by the trigger is captured before this transition writes its complete vector',async t=>{const p=twoOutputs();p.control.machines[0].states[0].transitions[0].conditions.push({tagId:'pump',op:'eq',value:0});const f=fixture(t,{p});await start(f);assert.equal(f.control.status().state,'automatic');assert.equal(f.control.status().machines[0].stateId,'supply');assert.deepEqual(f.writes,[{id:'pump',value:1},{id:'pump2',value:1}])});
test('a timeout during a multi-output transition prevents the remaining write and records the machine identity',async t=>{const p=twoOutputs();p.control.machines[0].states[0].timeoutMs=2000;let f;f=fixture(t,{p,write:async(id,value,values)=>{values[id].value=value;f.advance(600);return {verified:true,value}}});await start(f);assert.equal(f.control.status().state,'fault');assert.equal(f.writes.length,1);assert.equal(f.values.pump.value,1);assert.equal(f.values.pump2.value,0);assert.equal(f.control.events().at(-1).machineId,'machine');assert.match(f.control.status().reason,/超时/)});
test('disabled broken dependencies remain editable but invalid graph structure is still rejected',async()=>{const p=project();const result=await applyOperations(p,{operations:[{op:'tag.delete',deviceId:'device',id:'pump'}]},validate);assert.equal(result.project.control.machines[0].enabled,false);assert.doesNotThrow(()=>validateControl(result.project));result.project.control.machines[0].states[0].transitions[0].to='missing';assert.throws(()=>validateControl(result.project),/跳转目标/)});
test('a configured return transition repeats the sequence while preserving the minimum switch interval',async t=>{const f=fixture(t);f.m.states[2].transitions.push({to:'idle',priority:0,afterMs:1000,holdMs:0,conditions:[]});await start(f);f.values.level.value=80;f.advance(1000);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'done');f.values.level.value=20;await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'done');f.advance(1000);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'idle');f.advance(1000);await f.control.tick();f.advance(500);await f.control.tick();assert.equal(f.control.status().machines[0].stateId,'supply');assert.equal(f.control.status().machines[0].transitions,4);assert.equal(f.writes.length,3)});
test('the importable three-step water demo validates and starts with stopped simulation outputs',()=>{const p=JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/water-steps.simplehmi.json'),'utf8'));assert.doesNotThrow(()=>validate(p));assert.equal(p.simulation,'water-transfer');assert.equal(p.control.rules.length,0);assert.equal(p.control.machines[0].states.length,3);assert.equal(p.devices[0].tags.find(t=>t.id==='pump_command').initial,0)});

test('expired authorization during a step finishes the issued readback and stops remaining actions',async t=>{let release,allowed=true;const f=fixture(t,{p:twoOutputs(),write:()=>new Promise(r=>release=r)});f.control.arm({authorization:()=>allowed,authorizedBy:'test_agent'});f.advance(1000);await f.control.tick();f.advance(500);const pending=f.control.tick();allowed=false;release({verified:true,value:1});await pending;assert.equal(f.control.status().state,'manual');assert.equal(f.writes.length,1);assert.match(f.control.status().reason,/授权/)});
