// Real headless Chrome UI acceptance, isolated FUXA data and an ephemeral port.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require('../../integrations/browser/node_modules/playwright-core');
const root=path.resolve(__dirname,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'flex-ui-')),artifacts=path.resolve(root,process.env.FLEXHMI_BROWSER_ARTIFACTS||path.join(os.tmpdir(),'flexhmi-browser-evidence'));fs.mkdirSync(artifacts,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){let last;for(let i=0;i<100;i++){try{const v=await fn();if(v)return v}catch(e){last=e}await sleep(150)}throw Error('UI acceptance timed out: '+(last?.message||''))}
(async()=>{
 const port=await new Promise(r=>{const s=net.createServer().listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})});let backend,browser,tab,logs='';
 try{
  backend=spawn(process.execPath,[path.join(root,'server/main.js')],{cwd:temp,env:{...process.env,SIMPLEHMI:'1',PORT:String(port),userDir:temp},stdio:['ignore','pipe','pipe']});backend.stdout.on('data',b=>logs+=b);backend.stderr.on('data',b=>logs+=b);
  const base=`http://127.0.0.1:${port}/simplehmi/`,api=async route=>(await fetch(base+'api/'+route)).json();await until(async()=> (await api('status')).ready);
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{channel:'chrome'})});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-CN'});tab=await context.newPage();const errors=[];tab.on('pageerror',e=>errors.push(e.message));
  const openConnections=()=>tab.getByRole('button',{name:'连接',exact:true}).click(),saveConnection=()=>tab.getByRole('button',{name:'保存连接',exact:true}).click(),saved=async()=>{const p=await api('project');return p.pages.find(p=>p.id==='overview')};
  await tab.goto(base);await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.getByLabel('管线名称',{exact:true}).fill('供水进水管（验收）');await tab.screenshot({path:path.join(artifacts,'FlexHMI-连接编辑.png')});await saveConnection();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').label==='供水进水管（验收）');
  await tab.locator('[data-edit-connection="supply_in"]').click();await tab.getByRole('button',{name:'交换起点和终点'}).click();await saveConnection();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').routeInfo.arrowDirection==='left');await tab.getByRole('button',{name:'撤销',exact:true}).click();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').from==='tank_1');
  await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.getByRole('button',{name:'删除这条管线'}).click();await until(async()=> (await saved()).connections.length===1);await tab.getByRole('button',{name:'撤销',exact:true}).click();await until(async()=> (await saved()).connections.length===2);
  await openConnections();await tab.getByLabel('从（起点）',{exact:true}).selectOption('tank_2');await tab.getByLabel('到（终点）',{exact:true}).selectOption('tank_1');await tab.getByLabel('管线名称',{exact:true}).fill('回流演示连接');await tab.getByLabel('布线方式',{exact:true}).selectOption('return');await tab.screenshot({path:path.join(artifacts,'FlexHMI-回流连接预览.png')});await saveConnection();await until(async()=> (await saved()).connections.length===3);
  await tab.getByRole('button',{name:'运行',exact:true}).click();await tab.getByRole('button',{name:'返回编辑'}).waitFor();assert.equal(await tab.locator('[data-edit-connection]').count(),0);await until(async()=>await tab.locator('[data-connection="supply_in"]').getAttribute('data-flow')==='flowing');await tab.getByRole('button',{name:'供水泵启停',exact:true}).click();await until(async()=>await tab.locator('[data-connection="supply_in"]').getAttribute('data-flow')==='stopped');await tab.getByRole('button',{name:'返回编辑'}).click();await tab.getByRole('button',{name:'连接',exact:true}).waitFor();await tab.reload();await tab.getByRole('button',{name:'连接',exact:true}).waitFor();assert.equal((await saved()).connections.length,3);await tab.screenshot({path:path.join(artifacts,'FlexHMI-连接画布.png')});
  await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();await tab.getByRole('button',{name:'连接外部 Agent'}).click();await tab.getByLabel('允许的操作范围').selectOption('engineering');assert.equal(JSON.parse(await tab.getByLabel('MCP 接入配置').inputValue()).mcpServers.flexhmi.env.FLEXHMI_ACCESS,'engineering');
  await tab.getByRole('button',{name:'工程与记录'}).click();const project=await api('project');await tab.locator('#agent-saved-project').selectOption(project.id);await tab.getByRole('button',{name:'预览加载',exact:true}).click();await tab.getByRole('button',{name:'应用此计划'}).waitFor({state:'visible'});await until(async()=>!(await tab.getByRole('button',{name:'应用此计划'}).isDisabled()));await tab.screenshot({path:path.join(artifacts,'FlexHMI-工程计划预览.png')});await tab.getByRole('button',{name:'应用此计划'}).click();await until(async()=>!(await tab.locator('#dialog').evaluate(d=>d.open)));assert.equal((await api('control/status')).state,'manual');
  await tab.setViewportSize({width:767,height:700});await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.screenshot({path:path.join(artifacts,'FlexHMI-窄屏连接编辑.png')});const bounds=await tab.locator('#dialog').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=768);const saveBounds=await tab.getByRole('button',{name:'保存连接',exact:true}).boundingBox();assert.ok(saveBounds.y>=bounds.y&&saveBounds.y+saveBounds.height<=bounds.y+bounds.height,'save action stays visible in the dialog');await tab.getByRole('button',{name:'关闭',exact:true}).click();
  assert.deepEqual(errors,[]);const result={passed:true,browser:'headless Chrome',isolatedData:true,connectionEditing:true,canvasHitTarget:true,reverseArrow:true,deleteUndo:true,returnRoute:true,persistReload:true,runtimeHidesEditing:true,runtimeFlowReflectsPump:true,mcpConfiguration:true,savedProjectPreviewApply:true,narrowDialog:true,desktopInteractiveTested:false};fs.writeFileSync(path.join(artifacts,'browser-acceptance.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){if(tab){await tab.screenshot({path:path.join(artifacts,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(artifacts,'failure.html'),await tab.content().catch(()=>''));}fs.writeFileSync(path.join(artifacts,'backend-failure.log'),logs);throw e}
 finally{await browser?.close();if(backend&&backend.exitCode===null&&!backend.signalCode)await new Promise(r=>{backend.once('exit',r);backend.kill('SIGTERM');setTimeout(()=>{backend.kill('SIGKILL');r()},3000).unref()});fs.rmSync(temp,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
