// Real headless Chrome UI acceptance, isolated FUXA data and an ephemeral port.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require('../../integrations/browser/node_modules/playwright-core');
const root=path.resolve(__dirname,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'flex-ui-')),artifacts=path.resolve(root,process.env.FLEXHMI_BROWSER_ARTIFACTS||path.join(os.tmpdir(),'flexhmi-browser-evidence'));fs.mkdirSync(artifacts,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){let last;for(let i=0;i<100;i++){try{const v=await fn();if(v)return v}catch(e){last=e}await sleep(150)}throw Error('UI acceptance timed out: '+(last?.message||''))}
(async()=>{
 const port=await new Promise(r=>{const s=net.createServer().listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})});let backend,browser,tab,logs='';
 try{
  backend=spawn(process.execPath,[path.join(root,'server/main.js')],{cwd:temp,env:{...process.env,SIMPLEHMI:'1',PORT:String(port),userDir:temp},stdio:['ignore','pipe','pipe']});backend.stdout.on('data',b=>logs+=b);backend.stderr.on('data',b=>logs+=b);
  const base=`http://127.0.0.1:${port}/simplehmi/`,api=async route=>(await fetch(base+'api/'+route)).json();await until(async()=> (await api('status')).ready);
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{channel:'chrome'})});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-CN'});tab=await context.newPage();const errors=[];tab.on('pageerror',e=>errors.push(e.message));
  const openConnections=()=>tab.getByRole('button',{name:'连接',exact:true}).click(),saveConnection=()=>tab.getByRole('button',{name:'保存连接',exact:true}).click(),saved=async()=>{const p=await api('project');return p.pages.find(p=>p.id==='overview')};
  await tab.goto(base);await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.getByLabel('管线名称',{exact:true}).fill('供水进水管（验收）');await tab.screenshot({path:path.join(artifacts,'FlexHMI-连接编辑.png')});await saveConnection();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').label==='供水进水管（验收）');
  await tab.locator('[data-edit-connection="supply_in"]').click();await tab.getByRole('button',{name:'交换起点和终点'}).click();await saveConnection();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').routeInfo.arrowDirection==='left');await tab.getByRole('button',{name:'撤销',exact:true}).click();await until(async()=> (await saved()).connections.find(e=>e.id==='supply_in').from==='tank_1');
  await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.getByRole('button',{name:'删除这条管线'}).click();await until(async()=> (await saved()).connections.length===1);await tab.getByRole('button',{name:'撤销',exact:true}).click();await until(async()=> (await saved()).connections.length===2);
  await openConnections();await tab.getByLabel('从（起点）',{exact:true}).selectOption('tank_2');await tab.getByLabel('到（终点）',{exact:true}).selectOption('tank_1');await tab.getByLabel('管线名称',{exact:true}).fill('回流演示连接');await tab.getByLabel('布线方式',{exact:true}).selectOption('return');await tab.screenshot({path:path.join(artifacts,'FlexHMI-回流连接预览.png')});await saveConnection();await until(async()=> (await saved()).connections.length===3);
  await tab.getByRole('button',{name:'运行',exact:true}).click();await tab.getByRole('button',{name:'返回编辑'}).waitFor();assert.equal(await tab.locator('[data-edit-connection]').count(),0);await until(async()=>await tab.locator('[data-connection="supply_in"]').getAttribute('data-flow')==='flowing');await tab.getByRole('button',{name:'供水泵启停',exact:true}).click();await until(async()=>await tab.locator('[data-connection="supply_in"]').getAttribute('data-flow')==='stopped');await tab.getByRole('button',{name:'返回编辑'}).click();await tab.getByRole('button',{name:'连接',exact:true}).waitFor();await tab.reload();await tab.getByRole('button',{name:'连接',exact:true}).waitFor();assert.equal((await saved()).connections.length,3);await tab.screenshot({path:path.join(artifacts,'FlexHMI-连接画布.png')});
  await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();await tab.getByRole('button',{name:'连接外部 Agent'}).click();await tab.getByLabel('允许的操作范围').selectOption('engineering');assert.equal(JSON.parse(await tab.getByLabel('MCP 接入配置').inputValue()).mcpServers.flexhmi.env.FLEXHMI_ACCESS,'engineering');
  await tab.getByRole('button',{name:'工程与记录'}).click();const project=await api('project');await tab.locator('#agent-saved-project').selectOption(project.id);await tab.getByRole('button',{name:'预览加载',exact:true}).click();await tab.getByRole('button',{name:'应用此计划'}).waitFor({state:'visible'});await until(async()=>!(await tab.getByRole('button',{name:'应用此计划'}).isDisabled()));await tab.screenshot({path:path.join(artifacts,'FlexHMI-工程计划预览.png')});await tab.getByRole('button',{name:'应用此计划'}).click();await until(async()=>!(await tab.locator('#dialog').evaluate(d=>d.open)));assert.equal((await api('control/status')).state,'manual');
  const beforeRevert=await api('project');
  await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();
  await tab.getByText('外部 Agent 操作计划',{exact:true}).click();await tab.locator('#agent-input').fill(JSON.stringify({summary:'浏览器恢复验收',operations:[{op:'project.configure',name:'即将恢复的工程名称'}]}));await tab.getByRole('button',{name:'检查并预览计划'}).click();await until(async()=>!(await tab.getByRole('button',{name:'应用此计划'}).isDisabled()));await tab.getByRole('button',{name:'应用此计划'}).click();await until(async()=>!(await tab.locator('#dialog').evaluate(d=>d.open)));assert.equal((await api('project')).name,'即将恢复的工程名称');
  await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();await tab.getByRole('button',{name:'工程与记录'}).click();await tab.getByRole('button',{name:'预览恢复：浏览器恢复验收',exact:true}).click();await until(async()=>!(await tab.getByRole('button',{name:'应用此计划'}).isDisabled()));assert.ok((await tab.locator('#agent-result').innerText()).includes('已经发出的设备指令不会撤销'));assert.equal((await api('project')).name,'即将恢复的工程名称');await tab.screenshot({path:path.join(artifacts,'FlexHMI-历史恢复预览.png')});await tab.getByText('逐项变更明细',{exact:true}).click();await tab.locator('.agent-object-change summary').first().click();assert.ok((await tab.locator('.agent-object-change table').first().innerText()).includes('即将恢复的工程名称'));assert.ok((await tab.locator('.agent-object-change table').first().innerText()).includes(beforeRevert.name));await tab.locator('.agent-object-change table').first().evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await until(async()=>{const table=await tab.locator('.agent-object-change table').first().boundingBox(),footer=await tab.locator('.agent-dialog>.dialog-actions').boundingBox();return table.y+table.height<=footer.y});await tab.screenshot({path:path.join(artifacts,'FlexHMI-恢复前后差异.png')});await tab.getByRole('button',{name:'应用此计划'}).click();await until(async()=>!(await tab.locator('#dialog').evaluate(d=>d.open)));assert.equal((await api('project')).name,beforeRevert.name);assert.equal((await api('control/status')).state,'manual');await tab.reload();await tab.getByRole('button',{name:'AI 工作台',exact:true}).waitFor();assert.equal((await api('project')).name,beforeRevert.name);
  await tab.getByRole('button',{name:'控制',exact:true}).click();await tab.locator('#machine-add').click();
  const field=p=>tab.locator(`[data-path="${p}"]`),fill=async(p,v)=>{await field(p).fill(String(v));await field(p).blur()};
  await fill('name','供水步骤验收');await fill('states.0.name','待机');await fill('states.0.transitions.0.afterMs',1000);await fill('states.1.name','供水');await fill('states.1.actions.0.value',1);
  await tab.locator('#machine-add-state').click();await fill('states.2.name','停机');await fill('states.2.actions.0.value',0);await tab.locator('[data-add-transition="1"]').click();await fill('states.1.transitions.0.afterMs',2500);
  await tab.locator('#machine-form').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await tab.screenshot({path:path.join(artifacts,'FlexHMI-步骤流程编辑.png')});
  await tab.getByRole('button',{name:'检查步骤流程',exact:true}).click();await until(async()=>!(await tab.locator('#control-apply').isDisabled()));await fill('name','供水步骤验收（修改后）');assert.equal(await tab.locator('#control-apply').isDisabled(),true);await fill('name','供水步骤验收');await tab.getByRole('button',{name:'检查步骤流程',exact:true}).click();await until(async()=>!(await tab.locator('#control-apply').isDisabled()));await tab.locator('#control-apply').click();await until(async()=> (await api('project')).control?.machines?.length===1);assert.equal((await api('control/status')).state,'manual');const sequence=(await api('project')).control.machines[0];assert.equal(sequence.states.length,3);assert.equal(sequence.states[1].actions[0].value,1);
  await tab.locator('#control-start').click();await until(async()=> (await api('control/status')).machines[0]?.stateName==='供水');assert.equal(Number((await api('values')).values.pump_command.value),1);
  await until(async()=> (await api('control/status')).machines[0]?.stateName==='停机');assert.equal(Number((await api('values')).values.pump_command.value),0);assert.equal((await api('control/status')).machines[0].writes,2);await until(async()=> (await tab.locator('[data-machine-status]').innerText()).includes('2 次已验证写入'));assert.equal(await tab.locator('.machine-flow [aria-current=step]').innerText(),'停机\n终点');assert.equal(await tab.locator('.machine-flow [aria-current=step] strong').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');await tab.locator('#control-machines').scrollIntoViewIfNeeded();await tab.screenshot({path:path.join(artifacts,'FlexHMI-步骤流程运行.png')});await tab.locator('#control-pause').click();assert.equal((await api('control/status')).state,'manual');await tab.getByRole('button',{name:'关闭',exact:true}).click();await tab.reload();await tab.getByRole('button',{name:'控制',exact:true}).waitFor();assert.equal((await api('project')).control.machines[0].name,'供水步骤验收');
  const beforeDrag=await api('project'),heading=tab.locator('.component[data-id="heading"]'),box=await heading.boundingBox();
  const dragSaved=tab.waitForResponse(r=>r.url().endsWith('/api/project')&&r.request().method()==='POST'&&!!r.headers()['x-history-id']);
  await tab.mouse.move(box.x+box.width/2,box.y+box.height/2);await tab.mouse.down();await tab.mouse.move(box.x+box.width/2+32,box.y+box.height/2+18,{steps:6});await tab.mouse.up();const dragRecord=(await dragSaved).headers()['x-history-id'];await until(async()=> (await api('project')).pages[0].components.find(c=>c.id==='heading').x!==beforeDrag.pages[0].components.find(c=>c.id==='heading').x);
  const labelSaved=tab.waitForResponse(r=>r.url().endsWith('/api/project')&&r.request().method()==='POST'&&!!r.headers()['x-history-id']);await tab.locator('#c-label').fill('手动编辑历史验收');await tab.locator('#c-label').blur();await labelSaved;
  await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();await tab.getByRole('button',{name:'工程与记录'}).click();await tab.locator('#history-source').selectOption('editor');await tab.locator(`[data-plan-id="${dragRecord}"]`).waitFor();await tab.locator(`[data-plan-id="${dragRecord}"]`).click();await tab.getByText('逐项变更明细',{exact:true}).click();await tab.locator('.agent-object-change summary').first().click();assert.ok((await tab.locator('.agent-object-change table').first().innerText()).includes('水平位置'));assert.equal(await tab.getByRole('button',{name:'应用此计划'}).isDisabled(),true);await tab.locator('.agent-object-change table').first().evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await until(async()=>{const table=await tab.locator('.agent-object-change table').first().boundingBox(),footer=await tab.locator('.agent-dialog>.dialog-actions').boundingBox();return table.y+table.height<=footer.y});await tab.screenshot({path:path.join(artifacts,'FlexHMI-编辑保存差异.png')});
  await tab.locator(`[data-revert-plan="${dragRecord}"]`).click();await until(async()=>!(await tab.getByRole('button',{name:'应用此计划'}).isDisabled()));await tab.getByRole('button',{name:'应用此计划'}).click();await until(async()=>!(await tab.locator('#dialog').evaluate(d=>d.open)));assert.deepEqual((await api('project')).pages,beforeDrag.pages);assert.equal((await api('control/status')).state,'manual');await tab.reload();await tab.getByRole('button',{name:'AI 工作台',exact:true}).waitFor();assert.deepEqual((await api('project')).pages,beforeDrag.pages);
  // Populate older saved records through the real HTTP API, then test pagination in the UI.
  for(let i=0;i<23;i++){const current=await api('agent/state');current.project.name='历史翻页样例 '+i;const r=await fetch(base+'api/project',{method:'POST',headers:{'Content-Type':'application/json','If-Match':current.revision},body:JSON.stringify(current.project)});assert.equal(r.status,200)}
  await tab.reload();await tab.getByRole('button',{name:'AI 工作台',exact:true}).click();await tab.getByRole('button',{name:'工程与记录'}).click();await tab.locator('#history-source').selectOption('editor');await until(async()=>await tab.locator('.agent-history-row').count()===20);assert.equal(await tab.locator('#history-more').isVisible(),true);await tab.locator('#history-more').click();await until(async()=>await tab.locator('.agent-history-row').count()>20);const historyIds=await tab.locator('[data-plan-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.planId));assert.equal(new Set(historyIds).size,historyIds.length);assert.ok(await tab.locator('.agent-history-row button[data-plan-id]').first().evaluate(e=>{const r=e.getBoundingClientRect(),s=e.querySelector('span').getBoundingClientRect();return s.x-r.x<20}));await tab.screenshot({path:path.join(artifacts,'FlexHMI-编辑历史筛选.png')});await tab.getByRole('button',{name:'关闭',exact:true}).click();
  await tab.setViewportSize({width:767,height:700});await openConnections();await tab.locator('#connection-existing').selectOption('supply_in');await tab.screenshot({path:path.join(artifacts,'FlexHMI-窄屏连接编辑.png')});const bounds=await tab.locator('#dialog').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=768);const saveBounds=await tab.getByRole('button',{name:'保存连接',exact:true}).boundingBox();assert.ok(saveBounds.y>=bounds.y&&saveBounds.y+saveBounds.height<=bounds.y+bounds.height,'save action stays visible in the dialog');await tab.getByRole('button',{name:'关闭',exact:true}).click();
  assert.deepEqual(errors,[]);const result={passed:true,browser:'headless Chrome',isolatedData:true,connectionEditing:true,canvasHitTarget:true,reverseArrow:true,deleteUndo:true,returnRoute:true,persistReload:true,runtimeHidesEditing:true,runtimeFlowReflectsPump:true,mcpConfiguration:true,savedProjectPreviewApply:true,historyRevertPreviewApply:true,stepFlowEditor:true,stepFlowVerifiedWrites:true,stepFlowReload:true,stepFlowPreviewInvalidation:true,editorSaveDiff:true,editorDragAndPropertyRestore:true,editorHistoryPagination:true,narrowDialog:true,desktopInteractiveTested:false};fs.writeFileSync(path.join(artifacts,'browser-acceptance.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){if(tab){await tab.screenshot({path:path.join(artifacts,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(artifacts,'failure.html'),await tab.content().catch(()=>''));}fs.writeFileSync(path.join(artifacts,'backend-failure.log'),logs);throw e}
 finally{await browser?.close();if(backend&&backend.exitCode===null&&!backend.signalCode)await new Promise(r=>{backend.once('exit',r);backend.kill('SIGTERM');setTimeout(()=>{backend.kill('SIGKILL');r()},3000).unref()});fs.rmSync(temp,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
