'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{promisify}=require('node:util');
const scrypt=promisify(crypto.scrypt),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const fail=(message,status=403)=>{throw Object.assign(Error(message),{status,code:status===401?'authentication-required':status===429?'login-rate-limited':'access-denied'})};
const safeEqual=(a,b)=>typeof a==='string'&&typeof b==='string'&&a.length===b.length&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b));
const publicRoutes=new Set(['/status','/access/status','/access/login']);
const readable=/^\/(status|project|projects|values|history\/[^/]+|control\/(status|events)|knowledge|agent\/(capabilities|state|schema|audit|projects(?:\/[^/]+)?|plans(?:\/[^/]+)?)|industry\/evaluations(?:\/[^/]+)?|ai\/jobs(?:\/[^/]+)?)$/;
const engineering=/^\/(agent\/plans(?:\/[^/]+\/(apply|cancel))?|industry\/(context|evaluations)|test|ai\/generate|ai\/jobs\/[^/]+\/cancel)$/;
const operating=/^\/(agent\/write|control\/(arm|pause))$/;
function createAccess({dir,base='',now=Date.now}){
 const folder=path.join(dir,'access'),file=path.join(folder,'policy.json');fs.mkdirSync(folder,{recursive:true,mode:0o700});
 let policy=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{version:1,enabled:false,tokens:[]};
 if(policy.version!==1||typeof policy.enabled!=='boolean'||!Array.isArray(policy.tokens)||(policy.enabled&&(!policy.owner?.salt||!policy.owner?.hash)))throw Error('访问保护配置损坏，请检查本机备份后恢复；未自动解除保护');
 const sessions=new Map(),cookieName='flexhmi_owner_'+hash(dir).slice(0,12);let attempts=[],queue=Promise.resolve();
 const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p};
 function audit(event){fs.appendFileSync(path.join(folder,'events.jsonl'),JSON.stringify({at:now(),...event})+'\n',{mode:0o600})}
 function persist(next){const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(next),{mode:0o600});fs.chmodSync(tmp,0o600);fs.renameSync(tmp,file);policy=next;}
 function metadata(t){return {id:t.id,label:t.label,scope:t.scope,physicalWrites:t.physicalWrites,createdAt:t.createdAt,expiresAt:t.expiresAt,revokedAt:t.revokedAt||null,expired:t.expiresAt<=now()}}
 function tokenFrom(req){const auth=req.headers?.authorization;if(auth!==undefined){if(typeof auth!=='string'||!/^Bearer [A-Za-z0-9_-]{40,100}$/.test(auth))fail('授权令牌格式无效',401);return {kind:'agent',hash:hash(auth.slice(7))}}const cookie=String(req.headers?.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='));return cookie?{kind:'owner',hash:hash(cookie.slice(cookieName.length+1))}:null;}
 function identify(req){const credential=tokenFrom(req);if(credential?.kind==='agent'){const t=policy.enabled&&policy.tokens.find(t=>safeEqual(t.hash,credential.hash)&&!t.revokedAt&&t.expiresAt>now());if(!t)fail('授权无效、已撤销或已过期',401);return {kind:'agent',id:t.id,label:t.label,scope:t.scope,physicalWrites:t.physicalWrites,credential:credential.hash}}
  if(credential?.kind==='owner'){const session=sessions.get(credential.hash);if(session&&session.expiresAt>now()&&policy.enabled)return {kind:'owner',id:'owner',scope:'full',physicalWrites:true,credential:credential.hash};}
  if(!policy.enabled)return {kind:'local',id:'local',scope:'full',physicalWrites:true};fail('请先登录 FlexHMI，或为 Agent 配置有效授权',401);
 }
 function current(auth){if(!auth)return false;if(auth.kind==='local')return !policy.enabled;if(!policy.enabled)return false;if(auth.kind==='owner')return (sessions.get(auth.credential)?.expiresAt||0)>now();return policy.tokens.some(t=>t.id===auth.id&&safeEqual(t.hash,auth.credential)&&!t.revokedAt&&t.expiresAt>now())}
 function owner(auth){if(!current(auth)||!['owner','local'].includes(auth.kind))fail('只有本机所有者可以管理访问授权')}
 function checkOrigin(req){const raw=req.headers?.host;let host;try{host=new URL('http://'+raw).hostname}catch{}if(!['127.0.0.1','localhost','[::1]'].includes(host))fail('仅接受本机地址访问');const origin=req.headers?.origin;if(origin&&origin!==`http://${raw}`&&origin!==`https://${raw}`)fail('禁止跨站访问');}
 function authorize(auth,method,route,body){if(!current(auth))fail('授权已失效',401);if(auth.kind!=='agent')return;
  let allowed=method==='GET'&&readable.test(route);if(method==='POST'&&['engineering','full'].includes(auth.scope)&&engineering.test(route))allowed=true;if(method==='POST'&&auth.scope==='full'&&operating.test(route))allowed=true;
  if(!allowed)fail('当前 Agent 授权不允许此操作');
  if((route==='/agent/write'||route==='/control/arm')&&body?.allowPhysical===true&&!auth.physicalWrites)fail('此 Agent 未获准写入真实设备');
 }
 function middleware(req,res,next){try{checkOrigin(req);if(publicRoutes.has(req.path)&&((req.method==='GET'&&req.path!=='/access/login')||(req.method==='POST'&&req.path==='/access/login')))return next();req.flexAuth=identify(req);authorize(req.flexAuth,req.method,req.path,req.body);if(req.flexAuth.kind==='agent'&&req.path==='/agent/plans'&&req.method==='POST')req.body.actor=req.flexAuth.id;next()}catch(e){res.status(e.status||403).json({error:e.message,code:e.code})}}
 function upstream(req,res,next){try{if(req.path===base+'/'||req.path.startsWith(base+'/simplehmi/'))return next();if(!policy.enabled)return next();checkOrigin(req);const auth=identify(req);if(auth.kind!=='owner')fail('工程师接口需要所有者登录');req.flexAuth=auth;next()}catch(e){if(req.method==='GET'&&String(req.headers.accept).includes('text/html'))return res.redirect(base+'/simplehmi/');res.status(e.status||403).json({error:e.message,code:e.code})}}
 function bindSockets(io){if(!io)return;io.use((socket,next)=>{try{checkOrigin(socket.request);const auth=identify(socket.request);if(auth.kind==='agent')fail('Agent 请通过受限工程接口操作，不能直接连接工程师通信');socket.flexAuth=auth;socket.use((packet,done)=>{if(!current(auth)){socket.disconnect(true);return done(Error('访问授权已失效'))}done()});next()}catch(e){next(Error(e.message))}});const timer=setInterval(()=>{for(const socket of io.sockets.sockets.values())if(socket.flexAuth&&!current(socket.flexAuth))socket.disconnect(true)},1000);timer.unref();}
 function issueSession(res){for(const [id,s] of sessions)if(s.expiresAt<=now())sessions.delete(id);if(sessions.size>=20)sessions.delete(sessions.keys().next().value);const token=crypto.randomBytes(32).toString('base64url');sessions.set(hash(token),{expiresAt:now()+43200000});res.setHeader('Set-Cookie',`${cookieName}=${token}; HttpOnly; SameSite=Strict; Path=${base||'/'}; Max-Age=43200`);}
 async function passwordRecord(password){if(typeof password!=='string'||password.length<12||password.length>1024)fail('密码需要 12–1024 个字符',400);const salt=crypto.randomBytes(16).toString('hex');return {salt,hash:(await scrypt(password,salt,64)).toString('hex')}}
 const route=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){res.status(e.status||400).json({error:e.message,code:e.code||'access-error'})}};
 function mount(router){
  router.get('/access/status',route(async(req,res)=>{let auth;try{auth=identify(req)}catch{}res.json({enabled:policy.enabled,authenticated:!!auth,kind:auth?.kind||null,scope:auth?.scope||null,sessionOnly:true})}));
  router.post('/access/enable',route(async(req,res)=>serial(async()=>{owner(req.flexAuth);if(policy.enabled)fail('访问保护已开启');const password=await passwordRecord(req.body.password);persist({version:1,enabled:true,owner:password,tokens:[]});audit({event:'protection-enabled'});issueSession(res);res.json({enabled:true})})));
  router.post('/access/login',route(async(req,res)=>{if(!policy.enabled)fail('当前未开启访问保护',400);attempts=attempts.filter(t=>now()-t<60000);if(attempts.length>=5)fail('尝试过于频繁，请一分钟后重试',429);attempts.push(now());const password=req.body.password;if(typeof password!=='string'||password.length>1024)fail('密码不正确',401);const observed=policy.owner,derived=(await scrypt(password,observed.salt,64)).toString('hex');if(!policy.enabled||policy.owner!==observed||!safeEqual(derived,observed.hash)){audit({event:'login-failed'});fail('密码不正确',401)}issueSession(res);audit({event:'owner-login'});res.json({authenticated:true})}));
  router.post('/access/logout',route(async(req,res)=>{owner(req.flexAuth);sessions.delete(req.flexAuth.credential);res.setHeader('Set-Cookie',`${cookieName}=; HttpOnly; SameSite=Strict; Path=${base||'/'}; Max-Age=0`);res.json({authenticated:false})}));
  router.post('/access/password',route(async(req,res)=>serial(async()=>{owner(req.flexAuth);if(!policy.enabled)fail('请先启用访问保护');const old=req.body.currentPassword;if(typeof old!=='string'||old.length>1024)fail('当前密码不正确',401);const checked=(await scrypt(old,policy.owner.salt,64)).toString('hex');if(!safeEqual(checked,policy.owner.hash))fail('当前密码不正确',401);const password=await passwordRecord(req.body.password);owner(req.flexAuth);persist({...policy,owner:password,tokens:policy.tokens.map(t=>({...t,revokedAt:t.revokedAt||now()}))});sessions.clear();issueSession(res);audit({event:'owner-password-changed',revokedAllAgents:true});res.json({changed:true,revokedAllAgents:true})})));
  router.get('/access/tokens',route(async(req,res)=>{owner(req.flexAuth);res.json({tokens:policy.tokens.map(metadata)})}));
  router.post('/access/tokens',route(async(req,res)=>serial(async()=>{owner(req.flexAuth);if(!policy.enabled)fail('请先启用访问保护');const {label,scope,days=30,physicalWrites=false}=req.body;if(typeof label!=='string'||!label.trim()||label.length>80||!['read','engineering','full'].includes(scope)||!Number.isInteger(days)||days<1||days>365||typeof physicalWrites!=='boolean'||(physicalWrites&&scope!=='full'))fail('授权名称、范围、有效期或真实写入许可无效',400);if(policy.tokens.filter(t=>!t.revokedAt&&t.expiresAt>now()).length>=20)fail('最多保留 20 个有效 Agent 授权，请先撤销不用的授权',400);const token=crypto.randomBytes(32).toString('base64url'),record={id:'key_'+crypto.randomUUID().replaceAll('-',''),hash:hash(token),label:label.trim(),scope,physicalWrites,createdAt:now(),expiresAt:now()+days*86400000};persist({...policy,tokens:[...policy.tokens,record]});audit({event:'agent-authorized',id:record.id,label:record.label,scope,physicalWrites});res.json({...metadata(record),token})})));
  router.post('/access/tokens/:id/revoke',route(async(req,res)=>serial(async()=>{owner(req.flexAuth);const token=policy.tokens.find(t=>t.id===req.params.id);if(!token)fail('找不到授权',404);persist({...policy,tokens:policy.tokens.map(t=>t.id===token.id?{...t,revokedAt:now()}:t)});audit({event:'agent-revoked',id:token.id});res.json({revoked:true})})));
 }
 return {middleware,upstream,bindSockets,mount,current,identify,authorize,enabled:()=>policy.enabled,actor:req=>req.flexAuth?.kind==='agent'?req.flexAuth.id:null};
}
module.exports={createAccess};
