'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto'),{pathToFileURL}=require('node:url');
const [root,artifacts,arch,phase]=process.argv.slice(2),{configuration,request}=require(path.join(root,'desktop/ipc/launcher.cjs'));const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{assert.equal(process.platform,'darwin');assert.equal(process.arch,arch);const c=configuration(root),service=await request(c,'status');assert.equal(service.ready,true);
async function api(route,body){const r=await fetch(service.origin+'/simplehmi/api/'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();assert.equal(r.ok,true,JSON.stringify(d));return d}
const snapshot=await api('agent/state');assert.ok(snapshot.project.devices.every(d=>d.protocol==='sim'));assert.equal((await api('control/status')).state,'manual');
if(phase==='exercise'){
const m=JSON.parse(fs.readFileSync(path.join(root,'build-provenance.json')));assert.equal(m.arch,arch);assert.equal(m.mcpIncluded,true);for(const [file,hash] of Object.entries(m.sourceFiles))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),hash,file);
const sqlite=require(path.join(root,'server/node_modules/sqlite3'));await new Promise((resolve,reject)=>{const db=new sqlite.Database(':memory:',e=>{if(e)return reject(e);db.get('select 1 as ok',(e,row)=>{db.close();if(e||row.ok!==1)reject(e||Error('SQLite failed'));else resolve()})})});await require(path.join(root,'server/node_modules/@serialport/bindings-cpp')).autoDetect().list();
await api('write',{tagId:'pump_command',value:0});await delay(1600);const held1=(await api('values')).values;await delay(1200);const held2=(await api('values')).values;assert.equal(held1.source_level.value,held2.source_level.value);assert.equal(held1.destination_level.value,held2.destination_level.value);
await api('write',{tagId:'pump_command',value:1});await delay(2000);const moving=(await api('values')).values;assert.ok(moving.source_level.value<held2.source_level.value);assert.ok(moving.destination_level.value>held2.destination_level.value);assert.equal(moving.total_volume.value,4.15);await api('write',{tagId:'pump_command',value:0});
const sdk=path.join(root,'integrations/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client');const {Client}=await import(pathToFileURL(path.join(sdk,'index.js'))),{StdioClientTransport}=await import(pathToFileURL(path.join(sdk,'stdio.js')));const env={...process.env,FLEXHMI_ACCESS:'full',FLEXHMI_PHYSICAL_WRITES:'0'};delete env.FLEXHMI_URL;
const client=new Client({name:'mac-installed-qa',version:'1.0.0'});const transport=new StdioClientTransport({command:process.execPath,args:[path.join(root,'integrations/mcp/server.mjs')],env,stderr:'pipe'});
transport.stderr.on('data',b=>process.stderr.write(b));
try{await client.connect(transport);assert.equal((await client.listTools()).tools.length,23);const result=await client.callTool({name:'flexhmi_state',arguments:{}});assert.notEqual(result.isError,true);assert.equal(result.structuredContent.project.id,snapshot.project.id)}finally{await client.close()}
const plan=await api('agent/plans',{expectedRevision:snapshot.revision,actor:'mac-package-qa',summary:'Mac 安装包保存恢复验收',operations:[{op:'project.configure',name:'macOS '+arch+' 保存验收'},{op:'page.upsert',page:{id:'mac_qa',name:'验收画面',width:640,height:480,background:'#ffffff',components:[{id:'value',kind:'number',label:'原水箱',x:60,y:60,w:220,h:90,tagId:'source_level'}]}}]});assert.equal(plan.blocked,false);assert.equal((await api('agent/plans/'+plan.id+'/apply',{})).status,'applied');
fs.writeFileSync(path.join(artifacts,'exercise.json'),JSON.stringify({arch,sourceCommit:m.sourceCommit,sourceFilesVerified:Object.keys(m.sourceFiles).length,mcpToolCount:23,ipcDiscovery:true,nativeDependencies:true,waterConserved:true,stopHoldsLevels:true,projectId:snapshot.project.id,instance:service.instance,pid:service.pid},null,2));
}else if(phase==='restore'){const old=JSON.parse(fs.readFileSync(path.join(artifacts,'exercise.json')));assert.equal(snapshot.project.name,'macOS '+arch+' 保存验收');assert.equal(snapshot.project.pages.find(p=>p.id==='mac_qa').components[0].tagId,'source_level');assert.notEqual(service.instance,old.instance);fs.writeFileSync(path.join(artifacts,'restore.json'),JSON.stringify({arch,projectId:snapshot.project.id,manualAfterRestart:true,bindingRestored:true},null,2))}else throw Error('Unknown phase');
console.log('PASS installed macOS package',arch,phase)})().catch(e=>{console.error(e);process.exitCode=1});
