const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loginPending;
export function showOwnerLogin(api){
 if(loginPending)return loginPending;
 loginPending=new Promise(resolve=>{const d=document.createElement('dialog');d.className='access-login';d.innerHTML='<form><img src="./assets/brand/app-icon-mono.png" alt="FlexHMI" width="48" height="48"><h2>登录 FlexHMI</h2><p>访问保护已启用。输入本机所有者密码以继续。</p><label>所有者密码<input name="password" type="password" autocomplete="current-password" required></label><p role="status"></p><button class="primary" type="submit">登录</button></form>';document.body.append(d);d.addEventListener('cancel',e=>e.preventDefault());d.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=d.querySelector('button');button.disabled=true;try{await api('/access/login',{password:d.querySelector('input').value});d.close();d.remove();loginPending=null;resolve()}catch(err){d.querySelector('[role=status]').textContent=err.message}finally{button.disabled=false}};d.showModal();d.querySelector('input').focus()});return loginPending;
}
export async function connectAccessPanel({area,api,getScope,onToken,onRevoke,onProtectionChange}){
 const root=document.createElement('section');root.className='access-panel';area.append(root);
 async function draw(){const status=await api('/access/status');root.innerHTML=`<h3>访问保护与 Agent 授权</h3><p>${status.enabled?'已启用访问保护。服务端会校验授权范围，未登录的请求将被拒绝。':'当前为可信本机模式。启用访问保护后，浏览器需要登录，Agent 必须使用授权令牌。'}</p>`;
  if(!status.enabled){root.insertAdjacentHTML('beforeend','<form id="access-enable-form"><label>设置所有者密码<input type="password" name="password" minlength="12" maxlength="1024" autocomplete="new-password" required></label><label>再次输入密码<input type="password" name="confirm" autocomplete="new-password" required></label><p class="hint">至少 12 个字符。请保管密码；启用后，现有未授权 Agent 将断开，自动控制需要重新启动。</p><button class="primary" type="submit">启用访问保护</button><p role="status"></p></form>');const form=root.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{const password=form.elements.password.value;if(password!==form.elements.confirm.value)throw Error('两次密码不一致');await api('/access/enable',{password});onProtectionChange?.(true);await draw()}catch(err){form.querySelector('[role=status]').textContent=err.message;b.disabled=false}};return}
  const inventory=await api('/access/tokens');root.insertAdjacentHTML('beforeend',`<form id="access-token-form"><div class="access-grid"><label>Agent 名称<input name="label" maxlength="80" placeholder="例如：方案设计助手" required></label><label>有效期<select name="days"><option value="7">7 天</option><option value="30" selected>30 天</option><option value="90">90 天</option></select></label></div><p>授权范围使用上方所选的操作范围，适用于本工作区全部工程。</p><label class="access-check"><input type="checkbox" name="physical">额外允许真实设备写入（仅“工程设计与模拟控制”可用，调用时仍需明确声明）</label><button class="primary" type="submit">创建授权并生成接入配置</button><p role="status"></p></form><h4>已有授权</h4><div class="access-tokens">${inventory.tokens.map(t=>`<article><div><strong>${esc(t.label)}</strong><small>${esc(({read:'只读',engineering:'工程设计',full:'工程与控制'})[t.scope])} · ${t.physicalWrites?'允许真实写入':'不允许真实写入'} · ${t.revokedAt?'已撤销':t.expired?'已过期':'到期 '+new Date(t.expiresAt).toLocaleDateString()}</small></div>${!t.revokedAt&&!t.expired?`<button data-revoke="${esc(t.id)}">撤销</button>`:''}</article>`).join('')||'<p class="hint">尚未创建 Agent 授权。</p>'}</div><details><summary>更改所有者密码</summary><form id="access-password-form"><label>当前密码<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>新密码<input name="password" type="password" minlength="12" maxlength="1024" autocomplete="new-password" required></label><label>再次输入新密码<input name="confirm" type="password" autocomplete="new-password" required></label><p>更改密码会退出其他所有者会话并撤销全部 Agent 授权，相关自动控制会停止后续写入。</p><button type="submit">更改密码并撤销旧授权</button><p role="status"></p></form></details><button id="access-logout">退出所有者登录</button>`);
  root.querySelector('#access-token-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),message=f.querySelector('[role=status]');b.disabled=true;try{const scope=getScope(),physicalWrites=f.elements.physical.checked;if(physicalWrites&&scope!=='full')throw Error('真实设备写入需要先选择工程设计与模拟控制范围');const token=await api('/access/tokens',{label:f.elements.label.value,days:Number(f.elements.days.value),scope,physicalWrites});onToken(token);await draw();root.querySelector('form [role=status]').textContent='授权已创建。令牌仅在上方配置显示这一次，请复制到你的 Agent 应用。'}catch(err){message.textContent=err.message;b.disabled=false}};
  for(const b of root.querySelectorAll('[data-revoke]'))b.onclick=async()=>{b.disabled=true;try{await api('/access/tokens/'+b.dataset.revoke+'/revoke',{});onRevoke(b.dataset.revoke);await draw()}catch(e){b.disabled=false;b.textContent=e.message}};
  root.querySelector('#access-password-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{if(f.elements.password.value!==f.elements.confirm.value)throw Error('两次新密码不一致');await api('/access/password',{currentPassword:f.elements.currentPassword.value,password:f.elements.password.value});onRevoke(null);await draw();root.querySelector('#access-token-form [role=status]').textContent='密码已更新，旧会话与 Agent 授权已撤销。'}catch(err){f.querySelector('[role=status]').textContent=err.message;b.disabled=false}};
  root.querySelector('#access-logout').onclick=async()=>{await api('/access/logout',{});location.reload()};
 }
 await draw();
}
