import {assessmentMarkup} from './knowledge-panel.mjs';
import {waterDemo} from './water-demo.mjs';
import {aiPanelMarkup,connectAiPanel} from './ai-panel.mjs';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function connectionMarkup(page){
 return `<svg class="connections-layer" width="${page.width}" height="${page.height}" viewBox="0 0 ${page.width} ${page.height}" aria-hidden="true"><defs><marker id="connection-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M0 0 L8 4 L0 8 Z" fill="#62686e"/></marker></defs>${(page.connections||[]).map(e=>e.routeStatus==='ok'?`<polyline data-connection="${escape(e.id)}" points="${e.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#62686e" stroke-width="3" stroke-linejoin="round" marker-end="url(#connection-arrow)"/>`:'').join('')}</svg>`;
}
export async function openAgentStudio({api,dialog,save,project,pageId,accept,toast,openKnowledge}){
 try{await save();const current=await api('/agent/state');let preview=null;
 const d=dialog('AI 工作台',`<p>工程操作先预览关联影响，再应用。外部 Agent 可以调用同一套本机接口。模型生成的工程也会先检查再预览；阈值控制规则可在控制面板启动，行业评估可引用本地资料和所选实时观测。</p>${aiPanelMarkup()}<div class="agent-actions"><label>系统类型<select id="agent-mode"><option value="visualization">数据可视化</option><option value="intelligent-control">智能控制</option><option value="industry-ai">行业 AI 系统</option></select></label><button id="agent-demo">生成示例工程计划</button><button id="agent-knowledge">行业知识库</button><button id="agent-layout">优化当前画面</button></div><details><summary>外部 Agent 操作计划</summary><p>读取 /simplehmi/api/agent/capabilities 与 /agent/state；提交 /agent/plans，再调用计划的 /apply。修改工程后旧计划会失效。</p><textarea id="agent-input" aria-label="结构化操作计划" spellcheck="false"></textarea><button id="agent-preview">检查并预览计划</button><label class="ai-task-label">已有计划 / 评估编号<input id="agent-existing-id" placeholder="plan_… 或 evaluation_…"></label><button id="agent-load-existing">打开已有结果</button></details><div id="agent-result" aria-live="polite">选择示例生成或自动优化，查看设备、变量、画面与布线的完整修改计划。</div><div class="dialog-actions"><button id="agent-apply" class="primary" disabled>应用此计划</button></div>`);
 d.classList.add('agent-dialog');d.addEventListener('close',()=>d.classList.remove('agent-dialog'),{once:true});
 const input=d.querySelector('#agent-input'),result=d.querySelector('#agent-result'),apply=d.querySelector('#agent-apply');
 input.value=JSON.stringify({summary:'按连接关系自动优化当前画面',operations:[{op:'page.optimize',pageId}]},null,2);
 function renderPlan(value){preview=value;const pg=preview.project.pages.find(p=>p.id===preview.project.activePageId)||preview.project.pages[0];const objects=pg.components.filter(c=>c.kind!=='flow');const x=Math.max(0,Math.min(0,...objects.map(c=>c.x))-32),y=Math.max(0,Math.min(0,...objects.map(c=>c.y))-32);const previewWidth=Math.max(320,...objects.map(c=>c.x+c.w+48)),previewHeight=Math.max(200,...objects.map(c=>c.y+c.h+48));
 result.innerHTML=`${assessmentMarkup(preview.assessment)}<h3>${escape(preview.summary)}</h3><p>状态：${preview.status==='applied'?'已应用':preview.expiresAt<=Date.now()?'已过期，请重新评估或预览':preview.status==='preview'?'等待应用':escape(preview.status)}</p><p>${preview.changes.length} 项对象变化 · ${preview.impacts.length} 项关联影响 · ${preview.diagnostics.length} 项布局诊断</p><ul>${preview.impacts.map(x=>`<li>${escape(x.message)}</li>`).join('')}${preview.diagnostics.map(x=>`<li>${escape(x.connectionId||'')} ${escape(x.message)}</li>`).join('')}</ul><svg class="agent-map" viewBox="${x} ${y} ${previewWidth} ${previewHeight}" role="img" aria-label="布局计划预览">${(pg.connections||[]).filter(e=>e.routeStatus==='ok').map(e=>`<polyline points="${e.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#747b81" stroke-width="3"/>`).join('')}${pg.components.filter(c=>c.kind!=='flow').map(c=>`<rect x="${c.x}" y="${c.y}" width="${c.w}" height="${c.h}" rx="8" fill="#f3f4f5" stroke="#a8afb5"/><text x="${c.x+c.w/2}" y="${c.y+c.h/2}" text-anchor="middle" font-size="18" fill="#242b31">${escape(c.label||c.id)}</text>`).join('')}</svg><details><summary>逐项变更明细</summary><ul>${preview.changes.map(x=>`<li>${escape(x.action)} · ${escape(x.entity)}</li>`).join('')}</ul></details>${preview.blocked?'<p class="agent-error">存在无法布线的连接，请修改计划后重试。</p>':''}`;apply.disabled=preview.blocked||preview.status!=='preview'||preview.expiresAt<=Date.now();d.querySelector('#ai-config-panel').open=false;d.querySelector('#agent-input').closest('details').open=false;requestAnimationFrame(()=>result.scrollIntoView({block:'start',behavior:'smooth'}));
 }
 async function plan(request){apply.disabled=true;result.textContent="正在检查工程依赖并计算布线…";try{renderPlan(await api("/agent/plans",{...request,expectedRevision:current.revision,actor:"studio"}));}catch(e){preview=null;result.textContent=e.message}}
 d.querySelector('#agent-knowledge').onclick=()=>{d.close();openKnowledge?.()};
 d.querySelector('#agent-mode').value=current.project.system?.mode||'visualization';
 d.querySelector('#agent-load-existing').onclick=async()=>{apply.disabled=true;preview=null;try{const id=d.querySelector('#agent-existing-id').value.trim();if(id.startsWith('plan_'))renderPlan(await api('/agent/plans/'+encodeURIComponent(id)));else if(id.startsWith('evaluation_')){const e=await api('/industry/evaluations/'+encodeURIComponent(id));if(e.plan)renderPlan(await api('/agent/plans/'+encodeURIComponent(e.plan.id)));else result.innerHTML=assessmentMarkup(e.assessment)+'<p>本次评估未提出工程修改。</p>';}else throw Error('请填写有效的计划或评估编号');}catch(e){result.textContent=e.message}};
 d.querySelector('#agent-preview').onclick=()=>{try{plan(JSON.parse(input.value))}catch(e){result.textContent='计划 JSON 格式无效：'+e.message}};
 d.querySelector('#agent-layout').onclick=()=>plan({summary:'自动优化当前画面，并重算所有关联连接',operations:[{op:'page.optimize',pageId}]});
 d.querySelector('#agent-demo').onclick=()=>{const request={summary:'新建双水箱供水：独立液位、守恒输送、启停与趋势',operations:[{op:'project.create',project:waterDemo(d.querySelector('#agent-mode').value)}]};input.value=JSON.stringify(request,null,2);plan(request)};
 await connectAiPanel({d,api,project:current.project,revision:current.revision,renderPlan,renderReport:a=>{preview=null;apply.disabled=true;result.innerHTML=assessmentMarkup(a)+'<p>本次评估未提出工程修改。</p>'},onBusy:busy=>{apply.disabled=true;preview=null;for(const id of ['#agent-demo','#agent-layout','#agent-preview','#agent-mode','#agent-knowledge'])d.querySelector(id).disabled=busy;if(busy)result.textContent='正在生成新计划，工程尚未修改…'}});
 apply.onclick=async()=>{if(!preview)return;apply.disabled=true;try{await api(`/agent/plans/${preview.id}/apply`,{});await accept(await api('/project'));d.close();toast('计划已应用，设备、画面和关联布线已同步')}catch(e){result.textContent=e.message;apply.disabled=false}};
 }catch(e){toast('无法打开 AI 工作台：'+e.message)}
}
