import {connectAssessmentHistory} from './assessment-history.mjs';
import {connectAccessPanel} from './access-panel.mjs';
import {connectProjectPanel} from './project-panel.mjs';
import {assessmentMarkup} from './knowledge-panel.mjs';
import {waterDemo} from './water-demo.mjs';
import {aiPanelMarkup,connectAiPanel} from './ai-panel.mjs';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fieldNames={name:'名称',label:'显示名称',x:'水平位置',y:'垂直位置',w:'宽度',h:'高度',tagId:'绑定变量',valueTag:'状态变量',enabled:'启用',inputTag:'输入变量',outputTag:'输出变量',version:'版本',content:'正文',source:'来源',system:'系统类型',from:'起点',to:'终点',routeMode:'布线方式',onThreshold:'启动阈值',offThreshold:'停止阈值',evidence:'依据',activePageId:'当前画面',color:'颜色',fontSize:'字号'};
function changeMarkup(change){const before=change.before||{},after=change.after||{},fields=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));const value=x=>x===undefined?'无':typeof x==='string'?x:JSON.stringify(x);return `<details class="agent-object-change"><summary>${escape(({added:'新增',removed:'删除',updated:'修改',archived:'归档',restored:'恢复'})[change.action]||change.action)} · ${escape(after.name||after.label||before.name||before.label||change.entity)}</summary>${fields.length?`<table><thead><tr><th>内容</th><th>应用前</th><th>应用后</th></tr></thead><tbody>${fields.map(k=>`<tr><th>${escape(fieldNames[k]||k)}</th><td>${escape(value(before[k]))}</td><td>${escape(value(after[k]))}</td></tr>`).join('')}</tbody></table>`:`<p>${escape(change.entity)}</p>`}</details>`;}
export function connectionFlowState(edge,values,tags,runtime,now=Date.now()){
 if(!runtime||!edge.tagId)return 'static';const tag=tags.find(t=>t.id===edge.tagId),v=values[edge.tagId];
 if(tag?.type!=='Bool')return 'static';
 if(!v||v.quality!=='good'||![true,false,0,1].includes(v.value)||!Number.isFinite(v.ts)||v.ts>now+1000||now-v.ts>Math.max(3500,(tag.polling||1000)*3))return 'stale';
 return Number(v.value)===1?'flowing':'stopped';
}
export function connectionMarkup(page,{interactive=false}={}){
 return `<svg class="connections-layer" width="${page.width}" height="${page.height}" viewBox="0 0 ${page.width} ${page.height}" ${interactive?'aria-label="设备连接，可点击编辑"':'aria-hidden="true"'}><defs><marker id="connection-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M0 0 L8 4 L0 8 Z" fill="#62686e"/></marker></defs>${(page.connections||[]).map(e=>{if(e.routeStatus!=='ok')return '';const points=e.points.map(p=>`${p.x},${p.y}`).join(' '),label=e.label||`${e.from} → ${e.to}`;return `<polyline points="${points}" fill="none" stroke="${escape(page.background||'#ffffff')}" stroke-width="7" stroke-linejoin="round"/><polyline data-connection="${escape(e.id)}" points="${points}" fill="none" stroke="#62686e" stroke-width="3" stroke-linejoin="round" marker-end="url(#connection-arrow)"/>${interactive?`<g class="connection-hit" data-edit-connection="${escape(e.id)}" role="button" tabindex="0" aria-label="编辑管线：${escape(label)}"><title>${escape(label)} · 点击编辑流向</title><polyline class="connection-hit-line" points="${points}" fill="none" stroke="transparent" stroke-width="16"/>${e.points.slice(1).map((p,i)=>{const a=e.points[i];return `<rect x="${Math.min(a.x,p.x)-8}" y="${Math.min(a.y,p.y)-8}" width="${Math.max(16,Math.abs(a.x-p.x)+16)}" height="${Math.max(16,Math.abs(a.y-p.y)+16)}" fill="transparent" stroke="none"/>`}).join('')}</g>`:''}`}).join('')}</svg>`;
}
export async function openAgentStudio({api,dialog,save,project,pageId,accept,toast,openKnowledge}){
 try{await save();const current=await api('/agent/state');let preview=null;
 const d=dialog('AI 工作台',`<p>工程操作先预览关联影响，再应用。外部 Agent 可以调用同一套本机接口。模型生成的工程也会先检查再预览；阈值控制规则可在控制面板启动，行业评估可引用本地资料和所选实时观测。</p>${aiPanelMarkup()}<div class="agent-actions"><label>本次生成类型<select id="agent-mode" aria-label="本次生成类型"><option value="visualization">数据可视化</option><option value="intelligent-control">智能控制</option><option value="industry-ai">行业 AI 系统</option></select></label><button id="agent-demo">生成示例工程计划</button><button id="agent-knowledge">行业知识库</button><button id="agent-layout">优化当前画面</button><button id="agent-connect">连接外部 Agent</button><button id="agent-manage">工程与记录</button><button id="agent-assessments">评估记录</button></div><div id="agent-connection" hidden></div><div id="agent-projects" hidden></div><div id="agent-assessments-panel" hidden></div><details><summary>外部 Agent 操作计划</summary><p>读取 /simplehmi/api/agent/capabilities 与 /agent/state；提交 /agent/plans，再调用计划的 /apply。修改工程后旧计划会失效。</p><textarea id="agent-input" aria-label="结构化操作计划" spellcheck="false"></textarea><button id="agent-preview">检查并预览计划</button><label class="ai-task-label">已有计划 / 评估编号<input id="agent-existing-id" placeholder="plan_… 或 evaluation_…"></label><button id="agent-load-existing">打开已有结果</button></details><div id="agent-result" aria-live="polite">选择示例生成或自动优化，查看设备、变量、画面与布线的完整修改计划。</div><div class="dialog-actions"><button id="agent-apply" class="primary" disabled>应用此计划</button></div>`);
 d.querySelector('.dialog-body').after(d.querySelector('.dialog-actions'));
 d.classList.add('agent-dialog');d.addEventListener('close',()=>d.classList.remove('agent-dialog'),{once:true});
 const input=d.querySelector('#agent-input'),result=d.querySelector('#agent-result'),apply=d.querySelector('#agent-apply');
 input.value=JSON.stringify({summary:'按连接关系自动优化当前画面',operations:[{op:'page.optimize',pageId}]},null,2);
 function renderPlan(value){preview=value;const pg=preview.project.pages.find(p=>p.id===preview.project.activePageId)||preview.project.pages[0];const objects=pg.components.filter(c=>c.kind!=='flow');const x=Math.max(0,Math.min(0,...objects.map(c=>c.x))-32),y=Math.max(0,Math.min(0,...objects.map(c=>c.y))-32);const previewWidth=Math.max(320,...objects.map(c=>c.x+c.w+48)),previewHeight=Math.max(200,...objects.map(c=>c.y+c.h+48));
 result.innerHTML=`${assessmentMarkup(preview.assessment)}<h3>${escape(preview.summary)}</h3><p>状态：${preview.status==='applied'?'已应用':preview.expiresAt<=Date.now()?'已过期，请重新评估或预览':preview.status==='preview'?'等待应用':escape(preview.status)}</p>${preview.recovery?`<p class="agent-recovery">${escape(preview.recovery.message)}</p>`:''}<p>${preview.changes.length} 项对象变化 · ${preview.impacts.length} 项关联影响 · ${preview.diagnostics.length} 项布局诊断</p><ul>${preview.impacts.map(x=>`<li>${escape(x.message)}</li>`).join('')}${preview.diagnostics.map(x=>`<li>${escape(x.connectionId||'')} ${escape(x.message)}</li>`).join('')}</ul><svg class="agent-map" viewBox="${x} ${y} ${previewWidth} ${previewHeight}" role="img" aria-label="布局计划预览">${(pg.connections||[]).filter(e=>e.routeStatus==='ok').map(e=>`<polyline points="${e.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#747b81" stroke-width="3"/>`).join('')}${pg.components.filter(c=>c.kind!=='flow').map(c=>`<rect x="${c.x}" y="${c.y}" width="${c.w}" height="${c.h}" rx="8" fill="#f3f4f5" stroke="#a8afb5"/><text x="${c.x+c.w/2}" y="${c.y+c.h/2}" text-anchor="middle" font-size="18" fill="#242b31">${escape(c.label||c.id)}</text>`).join('')}</svg><details><summary>逐项变更明细</summary>${preview.changes.map(changeMarkup).join('')}</details>${preview.blocked?'<p class="agent-error">存在无法布线的连接，请修改计划后重试。</p>':''}`;apply.disabled=preview.blocked||preview.status!=='preview'||preview.expiresAt<=Date.now();d.querySelector('#ai-config-panel').open=false;d.querySelector('#agent-input').closest('details').open=false;requestAnimationFrame(()=>result.scrollIntoView({block:'start',behavior:'smooth'}));
 }
 async function plan(request){apply.disabled=true;result.textContent="正在检查工程依赖并计算布线…";try{renderPlan(await api("/agent/plans",{...request,expectedRevision:current.revision,actor:"studio"}));}catch(e){preview=null;result.textContent=e.message}}
 connectProjectPanel({d,api,plan,renderPlan,onError:e=>{preview=null;apply.disabled=true;result.textContent=e.message}});
 d.querySelector('#agent-connect').onclick=async()=>{const area=d.querySelector('#agent-connection');area.hidden=false;area.textContent='正在准备连接配置…';try{const info=await api('/agent/mcp-config');area.innerHTML=`<div class="agent-connection-card"><h3>连接你的 Agent 应用</h3><p>${escape(info.message)}</p><p>${escape(info.scopeNote)}</p><label>允许的操作范围<select id="agent-access"><option value="full">工程设计与模拟控制</option><option value="engineering">工程设计</option><option value="read">只读检查</option></select></label><textarea id="agent-connect-json" aria-label="MCP 接入配置" readonly spellcheck="false"></textarea><button id="agent-copy-config" ${info.installed?'':'disabled'}>复制接入配置</button><span id="agent-copy-result" role="status"></span></div>`;const field=area.querySelector('#agent-connect-json');function update(){info.configuration.mcpServers.flexhmi.env.FLEXHMI_ACCESS=area.querySelector('#agent-access').value;field.value=JSON.stringify(info.configuration,null,2);area.querySelector('#agent-copy-config').disabled=!info.installed||(info.protectedMode&&!info.configuration.mcpServers.flexhmi.env.FLEXHMI_TOKEN);}update();area.querySelector('#agent-access').onchange=()=>{delete info.configuration.mcpServers.flexhmi.env.FLEXHMI_TOKEN;update()};area.querySelector('#agent-copy-config').onclick=async()=>{const status=area.querySelector('#agent-copy-result');try{await navigator.clipboard.writeText(field.value);status.textContent='已复制，在 Agent 应用的 MCP 设置中粘贴。';}catch{field.focus();field.select();status.textContent='已选中配置，请复制后粘贴到 Agent 应用。';}};let issuedId=null;await connectAccessPanel({area,api,onProtectionChange:enabled=>{info.protectedMode=enabled;update()},getScope:()=>area.querySelector('#agent-access').value,onToken:t=>{issuedId=t.id;Object.assign(info.configuration.mcpServers.flexhmi.env,{FLEXHMI_TOKEN:t.token,FLEXHMI_ACCESS:t.scope,FLEXHMI_PHYSICAL_WRITES:t.physicalWrites?'1':'0'});update();field.scrollIntoView({block:'center',behavior:'smooth'});},onRevoke:id=>{if(id===null||id===issuedId){delete info.configuration.mcpServers.flexhmi.env.FLEXHMI_TOKEN;update()}}});area.scrollIntoView({block:'start',behavior:'smooth'});}catch(e){area.textContent=e.message}};
 d.querySelector('#agent-knowledge').onclick=()=>{d.close();openKnowledge?.()};
 d.querySelector('#agent-mode').value=current.project.system?.mode||'visualization';
 function renderReport(a,id){preview=null;apply.disabled=true;result.innerHTML=assessmentMarkup(a)+'<p>本次评估未提出工程修改。报告已保存，可在评估记录中重开；历史观测不代表当前状态。</p>'+(id?'<p class="hint">报告编号：'+escape(id)+'</p>':'');result.scrollIntoView({block:'start',behavior:'smooth'});}
 async function openEvaluation(id){apply.disabled=true;preview=null;const e=await api('/industry/evaluations/'+encodeURIComponent(id));if(e.plan)renderPlan(await api('/agent/plans/'+encodeURIComponent(e.plan.id)));else renderReport(e.assessment,e.id);}
 connectAssessmentHistory({d,api,projectId:current.project.id,openEvaluation,onError:e=>{preview=null;apply.disabled=true;result.textContent=e.message}});
 d.querySelector('#agent-load-existing').onclick=async()=>{apply.disabled=true;preview=null;try{const id=d.querySelector('#agent-existing-id').value.trim();if(id.startsWith('plan_'))renderPlan(await api('/agent/plans/'+encodeURIComponent(id)));else if(id.startsWith('evaluation_'))await openEvaluation(id);else throw Error('请填写有效的计划或评估编号');}catch(e){result.textContent=e.message}};
 d.querySelector('#agent-preview').onclick=()=>{try{plan(JSON.parse(input.value))}catch(e){result.textContent='计划 JSON 格式无效：'+e.message}};
 d.querySelector('#agent-layout').onclick=()=>plan({summary:'自动优化当前画面，并重算所有关联连接',operations:[{op:'page.optimize',pageId}]});
 d.querySelector('#agent-demo').onclick=()=>{const request={summary:'新建双水箱供水：独立液位、守恒输送、启停与趋势',operations:[{op:'project.create',project:waterDemo(d.querySelector('#agent-mode').value)}]};input.value=JSON.stringify(request,null,2);plan(request)};
 await connectAiPanel({d,api,project:current.project,revision:current.revision,renderPlan,renderReport,onBusy:busy=>{apply.disabled=true;preview=null;for(const id of ['#agent-demo','#agent-layout','#agent-preview','#agent-mode','#agent-knowledge','#agent-assessments','#agent-load-existing'])d.querySelector(id).disabled=busy;if(busy)result.textContent='正在生成新计划，工程尚未修改…'}});
 apply.onclick=async()=>{if(!preview)return;apply.disabled=true;try{await api(`/agent/plans/${preview.id}/apply`,{});await accept(await api('/project'));d.close();toast('计划已应用，设备、画面和关联布线已同步')}catch(e){result.textContent=e.message;apply.disabled=false}};
 }catch(e){toast('无法打开 AI 工作台：'+e.message)}
}
