const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function aiPanelMarkup(){return `<section class="ai-compose"><div class="ai-compose-heading"><strong>描述你想搭建的系统</strong><span id="ai-provider-status">正在读取模型配置…</span></div><label class="ai-task-label">工作方式<select id="ai-task"><option value="generate">生成 / 修改工程</option><option value="assess">依据知识评估当前系统</option></select></label><div id="ai-evidence-options" hidden></div><textarea id="ai-prompt" aria-label="工程需求" placeholder="例如：新建一个双水箱供水系统，包含进水泵、出水阀、水位和流量模拟值，再增加一张趋势画面。"></textarea><div class="ai-compose-tools"><button id="ai-generate" class="primary" disabled>生成工程计划</button><button id="ai-cancel" hidden>取消生成</button><span id="ai-job-status" role="status"></span></div><details id="ai-config-panel"><summary>模型服务设置</summary><div class="ai-config-grid"><label>服务类型<select id="ai-provider"><option value="openai-compatible">OpenAI 兼容接口</option><option value="ollama">本机 Ollama</option></select></label><label>模型名称<input id="ai-model" placeholder="填写服务商提供的模型名" autocomplete="off"></label><label class="ai-wide">服务地址<input id="ai-base-url" placeholder="https://服务商地址/v1" autocomplete="off"></label><label class="ai-wide">API 密钥<input id="ai-key" type="password" autocomplete="new-password" placeholder="仅保留到服务关闭，不写入工程文件"></label><label>生成等待时间（秒）<input id="ai-timeout" type="number" min="30" max="900" step="1" value="120" aria-describedby="ai-timeout-note"></label><p id="ai-timeout-note" class="hint">本机模型生成复杂工程可能需要更久，最长可等待 15 分钟。行业评估仍需在观测的 3 分钟有效期内完成。</p><label class="ai-wide ai-check"><input id="ai-json-mode" type="checkbox" checked>要求 JSON 输出（兼容服务不支持时可关闭）</label></div><p class="ai-data-note">生成时，会把需求和当前工程结构（含设备地址、变量和画面配置）发送至你填写的服务；普通生成不发送实时数值；行业评估会额外发送所选资料和变量的本次观测值。不发送历史曲线或其他本机凭据。Ollama 只连接本机。</p><div class="ai-compose-tools"><button id="ai-save-config">保存模型设置</button><button id="ai-clear-key">清除会话密钥</button><span id="ai-config-status" role="status"></span></div></details></section>`}
export async function connectAiPanel({d,api,project,revision,renderPlan,renderReport,onBusy}){
 const $=s=>d.querySelector(s),generate=$('#ai-generate'),cancel=$('#ai-cancel'),status=$('#ai-job-status');
 let currentJob=null,timer=null,closed=false,busy=false;
 const entries=project.knowledge||[],tags=project.devices.flatMap(dev=>dev.tags.map(t=>({...t,deviceName:dev.name})));
 $('#ai-evidence-options').innerHTML=`<p class="hint">评估只使用选中的资料与当前观测。资料正文是参考数据，不赋予执行权限。未选择资料时按需求检索；资料来源需自行复核。</p><details><summary>选择资料（最多 8 条）</summary><div class="ai-evidence-list">${entries.map((e,i)=>`<label><input type="checkbox" data-ai-entry="${esc(e.id)}" ${i<8&&(!e.validUntil||Date.parse(e.validUntil)>Date.now())?'checked':''}>${esc(e.title)} · v${e.version}${e.validUntil&&Date.parse(e.validUntil)<=Date.now()?' · 已过期':''}</label>`).join('')||'暂无资料，请先打开行业知识库。'}</div></details><details><summary>选择观测变量（最多 30 个）</summary><div class="ai-evidence-list">${tags.map((t,i)=>`<label><input type="checkbox" data-ai-observe="${esc(t.id)}" ${i<4?'checked':''}>${esc(t.deviceName)} / ${esc(t.name)}</label>`).join('')}</div></details><p class="ai-data-note">点击评估将把所选资料和变量当前值发送到已配置的模型服务。当前工程需先启用“行业 AI”模式。</p>`;
 $('#ai-task').onchange=()=>{const assess=$('#ai-task').value==='assess';$('#ai-evidence-options').hidden=!assess;generate.textContent=assess?'评估并生成建议':'生成工程计划';};

 function setBusy(value){busy=value;generate.disabled=value;cancel.hidden=!value;onBusy(value);for(const id of ['#ai-save-config','#ai-clear-key','#ai-task'])$(id).disabled=value;}
 function showConfig(c){$('#ai-provider-status').textContent=c.configured?`${c.model} · ${c.provider==='ollama'?'本机':'兼容接口'}${c.hasSessionKey?' · 密钥已填写':''}`:'尚未配置模型';generate.disabled=!c.configured||busy;
 if(c.configured){$('#ai-provider').value=c.provider;$('#ai-base-url').value=c.baseUrl;$('#ai-model').value=c.model;$('#ai-json-mode').checked=c.jsonMode;$('#ai-timeout').value=c.timeoutSeconds||120;}}
 $('#ai-provider').onchange=()=>{const ollama=$('#ai-provider').value==='ollama';$('#ai-base-url').value=ollama?'http://127.0.0.1:11434':'';$('#ai-key').value='';$('#ai-json-mode').disabled=ollama;};
 $('#ai-save-config').onclick=async()=>{try{const body={provider:$('#ai-provider').value,baseUrl:$('#ai-base-url').value.trim(),model:$('#ai-model').value.trim(),jsonMode:$('#ai-json-mode').checked,timeoutSeconds:Number($('#ai-timeout').value)};if($('#ai-key').value)body.apiKey=$('#ai-key').value;const config=await api('/ai/config',body);$('#ai-key').value='';showConfig(config);$('#ai-config-status').textContent='设置已保存；服务地址已变更时，旧密钥会自动清除。'}catch(e){$('#ai-config-status').textContent=e.message}};
 $('#ai-clear-key').onclick=async()=>{try{showConfig(await api('/ai/clear-key',{}));$('#ai-key').value='';$('#ai-config-status').textContent='会话密钥已清除'}catch(e){$('#ai-config-status').textContent=e.message}};
 async function poll(){if(closed||!currentJob)return;try{const job=await api('/ai/jobs/'+currentJob);if(closed)return;status.textContent=job.error||(job.status==='running'?`${job.stage} · 已用 ${Math.floor((job.elapsedMs||0)/1000)} 秒 / 最多 ${Math.ceil(job.timeoutSeconds||120)} 秒`:job.stage);
 if(job.status==='running'){timer=setTimeout(poll,700);return;}currentJob=null;setBusy(false);if(job.status==='ready'){if(job.plan)renderPlan(job.plan);else if(job.report)renderReport(job.report,job.evaluationId);}
 }catch(e){status.textContent=e.message;currentJob=null;setBusy(false)}}
 generate.onclick=async()=>{if(busy)return;setBusy(true);status.textContent='正在提交需求…';try{const task=$('#ai-task').value,knowledgeIds=[...d.querySelectorAll('[data-ai-entry]:checked')].map(e=>e.dataset.aiEntry),observedTagIds=[...d.querySelectorAll('[data-ai-observe]:checked')].map(e=>e.dataset.aiObserve);const job=await api('/ai/generate',{task,...(task==='assess'?{observedTagIds,...(knowledgeIds.length?{knowledgeIds}:{})}:{}),prompt:$('#ai-prompt').value,expectedRevision:revision,mode:$('#agent-mode').value});currentJob=job.id;if(closed){await api('/ai/jobs/'+currentJob+'/cancel',{});return;}poll();}catch(e){if(!closed){status.textContent=e.message;setBusy(false)}}};
 cancel.onclick=async()=>{if(!currentJob)return;try{await api('/ai/jobs/'+currentJob+'/cancel',{});clearTimeout(timer);currentJob=null;setBusy(false);status.textContent='已取消，工程未修改'}catch(e){status.textContent=e.message}};
 d.addEventListener('close',()=>{closed=true;clearTimeout(timer);if(currentJob)api('/ai/jobs/'+currentJob+'/cancel',{}).catch(()=>{});$('#ai-key').value='';},{once:true});
 try{const config=await api('/ai/config');if(!closed){showConfig(config);if(!config.configured)$('#ai-config-panel').open=true}}catch(e){$('#ai-provider-status').textContent=e.message;}
}
