const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={manual:'人工接管',automatic:'自动控制运行中',fault:'自动控制已中止'};
export async function openControlPanel({api,dialog,save,accept,toast}){
 try{
  await save();let current=await api('/agent/state'),preview=null,editing=null,closed=false,timer;
  const d=dialog('自动控制',`<div class="control-status"><strong id="control-state">正在读取…</strong><p id="control-reason"></p><div class="control-commands"><button class="primary" id="control-start">启动自动控制</button><button class="secondary" id="control-pause">人工接管</button></div><div id="control-physical"></div><p class="hint">人工接管只停止后续自动写入，不自动改变设备当前输出。数据过期、外部改值或回读失败会中止规则。</p></div><div class="control-rule-heading"><strong>控制规则</strong><button class="secondary" id="control-add">添加规则</button></div><div id="control-rules"></div><form id="control-form" hidden></form><div id="control-preview" aria-live="polite"></div><div class="dialog-actions"><button class="primary" id="control-apply" disabled>应用规则修改</button></div><details><summary>最近控制记录</summary><div id="control-events"></div></details>`);
  d.classList.add('control-dialog');const $=s=>d.querySelector(s);
  const tags=()=>current.project.devices.flatMap(dev=>dev.tags.map(t=>({...t,deviceName:dev.name,protocol:dev.protocol})));
  function list(){
   const rules=current.project.control?.rules||[];
   $('#control-rules').innerHTML=rules.length?rules.map(r=>`<article class="control-rule"><div><strong>${esc(r.name)}</strong><span>${r.enabled?'已启用':'已停用'}</span></div><p>${esc(tags().find(t=>t.id===r.inputTag)?.name||r.inputTag)} ${r.direction==='low'?'≤':'≥'} ${r.onThreshold} → 写入 ${r.onValue}；${r.direction==='low'?'≥':'≤'} ${r.offThreshold} → 写入 ${r.offValue}</p><p class="hint">输出：${esc(tags().find(t=>t.id===r.outputTag)?.name||r.outputTag)}${r.invalidReason?' · '+esc(r.invalidReason):''}</p><div><button data-edit-rule="${esc(r.id)}">编辑</button><button data-remove-rule="${esc(r.id)}">删除</button><span data-rule-status="${esc(r.id)}"></span></div></article>`).join(''):'<p class="hint">添加一条输入条件与输出动作，或让 AI 生成规则。</p>';
   for(const b of d.querySelectorAll('[data-edit-rule]'))b.onclick=()=>form(rules.find(r=>r.id===b.dataset.editRule));
   for(const b of d.querySelectorAll('[data-remove-rule]'))b.onclick=()=>plan([{op:'rule.delete',id:b.dataset.removeRule}],'删除控制规则，并暂停自动控制');
   const physical=rules.filter(r=>r.enabled&&tags().find(t=>t.id===r.outputTag)?.protocol!=='sim').map(r=>r.outputTag);
   $('#control-physical').innerHTML=physical.length?`<label class="control-consent"><input type="checkbox" id="control-authorize">本次会话允许规则向以下真实设备点位写入：${physical.map(id=>esc(tags().find(t=>t.id===id)?.name||id)).join('、')}</label>`:'';
   $('#control-start').textContent=physical.length?'启动真实设备自动控制':'启动自动控制';
  }
  function input(label,key,value,type='number'){return `<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''} required></label>`}
  function select(label,key,value,options){return `<label>${label}<select name="${key}">${options.map(([id,name])=>`<option value="${esc(id)}" ${value===id?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`}
  function form(existing){
   const all=tags(),out=all.filter(t=>t.writable&&!['100000','300000'].includes(String(t.memory)));
   if(!all.length||!out.length){toast('请先添加输入变量和一个可写输出变量');return;}
   editing=existing?.id||'rule_'+crypto.randomUUID().replaceAll('-','').slice(0,12);
   const r=existing||{name:'自动控制规则',inputTag:all[0].id,outputTag:out[0].id,direction:'low',onThreshold:30,offThreshold:70,onValue:1,offValue:0,outputMin:0,outputMax:1,holdMs:1000,minIntervalMs:2000,maxAgeMs:3500,guards:[],enabled:true};
   const opts=all.map(t=>[t.id,`${t.deviceName} / ${t.name}`]);
   $('#control-form').hidden=false;$('#control-form').innerHTML=`<h3>${existing?'编辑':'添加'}规则</h3><div class="control-grid">${input('规则名称','name',r.name,'text')}${select('输入变量','inputTag',r.inputTag,opts)}${select('输出变量','outputTag',r.outputTag,out.map(t=>[t.id,t.name]))}${select('触发方向','direction',r.direction,[['low','低于阈值启动'],['high','高于阈值启动']])}${input('启动阈值','onThreshold',r.onThreshold)}${input('停止阈值','offThreshold',r.offThreshold)}${input('启动写入值','onValue',r.onValue)}${input('停止写入值','offValue',r.offValue)}</div><details><summary>约束与允许条件</summary><div class="control-grid">${input('允许输出下限','outputMin',r.outputMin)}${input('允许输出上限','outputMax',r.outputMax)}${input('条件稳定时间（毫秒）','holdMs',r.holdMs)}${input('最小写入间隔（毫秒）','minIntervalMs',r.minIntervalMs)}${input('数据最长时效（毫秒）','maxAgeMs',r.maxAgeMs)}</div><p class="hint">允许条件全部满足才可启动。不满足时请求关闭；数据失效时停止自动写入，需人工确认设备状态。</p><div id="control-guards"></div><button type="button" id="control-guard-add">添加允许条件</button></details><label class="control-consent"><input name="enabled" type="checkbox" ${r.enabled?'checked':''}>启用这条规则</label><div class="control-commands"><button class="primary" type="submit">检查规则修改</button><button type="button" id="control-form-close">取消编辑</button></div>`;
   const guards=r.guards.map(g=>({...g}));
   function drawGuards(){ $('#control-guards').innerHTML=guards.map((g,i)=>`<div class="control-guard" data-guard="${i}">${select('变量','guard-tag',g.tagId,opts)}${select('比较','guard-op',g.op,[['gt','>'],['gte','≥'],['lt','<'],['lte','≤'],['eq','='],['ne','≠']])}${input('阈值','guard-value',g.value)}<button type="button" data-remove-guard="${i}">移除</button></div>`).join('');for(const b of d.querySelectorAll('[data-remove-guard]'))b.onclick=()=>{readGuards();guards.splice(+b.dataset.removeGuard,1);drawGuards()};}
   function readGuards(){for(const row of d.querySelectorAll('[data-guard]'))guards[+row.dataset.guard]={tagId:row.querySelector('[name=guard-tag]').value,op:row.querySelector('[name=guard-op]').value,value:Number(row.querySelector('[name=guard-value]').value)};}
   drawGuards();$('#control-guard-add').onclick=()=>{readGuards();if(guards.length<16){guards.push({tagId:all[0].id,op:'gt',value:0});drawGuards()}};
   $('#control-form-close').onclick=()=>{$('#control-form').hidden=true};
   $('#control-form').onsubmit=e=>{e.preventDefault();readGuards();const data=new FormData(e.currentTarget),rule={id:editing,enabled:data.get('enabled')==='on',guards:[...guards]};for(const key of ['name','inputTag','outputTag','direction'])rule[key]=data.get(key);for(const key of ['onThreshold','offThreshold','onValue','offValue','outputMin','outputMax','holdMs','minIntervalMs','maxAgeMs'])rule[key]=Number(data.get(key));plan([{op:'project.configure',mode:current.project.system?.mode==='industry-ai'?'industry-ai':'intelligent-control'},{op:'rule.upsert',rule}],'修改控制规则，应用后保持人工接管');};
  }
  async function plan(operations,summary){preview=null;$('#control-apply').disabled=true;try{preview=await api('/agent/plans',{expectedRevision:current.revision,actor:'control-panel',summary,operations});$('#control-preview').innerHTML=`<h3>${esc(summary)}</h3><p>${preview.changes.length} 项对象变化</p><ul>${[...preview.impacts,...preview.diagnostics].map(i=>`<li>${esc(i.message)}</li>`).join('')}</ul>`;$('#control-apply').disabled=preview.blocked;}catch(e){$('#control-preview').textContent=e.message}}
  $('#control-apply').onclick=async()=>{if(!preview)return;$('#control-apply').disabled=true;try{await api(`/agent/plans/${preview.id}/apply`,{});await accept(await api('/project'));current=await api('/agent/state');preview=null;$('#control-form').hidden=true;$('#control-preview').textContent='规则已保存。';list();}catch(e){$('#control-preview').textContent=e.message}};
  $('#control-add').onclick=()=>form();
  $('#control-start').onclick=async()=>{try{const physicalTargets=(current.project.control?.rules||[]).filter(r=>r.enabled&&tags().find(t=>t.id===r.outputTag)?.protocol!=='sim').map(r=>r.outputTag);await api('/control/arm',{expectedRevision:current.revision,allowPhysical:!!$('#control-authorize')?.checked,physicalTargets});await poll(false);}catch(e){$('#control-reason').textContent=e.message;toast(e.message)}};
  $('#control-pause').onclick=async()=>{try{await api('/control/pause',{});await poll(false)}catch(e){toast(e.message)}};
  async function poll(schedule=true){try{const s=await api('/control/status');if(closed)return;$('#control-state').textContent=labels[s.state]||s.state;$('#control-reason').textContent=s.reason;$('#control-start').disabled=s.state==='automatic';for(const r of s.rules){const node=[...d.querySelectorAll('[data-rule-status]')].find(n=>n.dataset.ruleStatus===r.id);if(node)node.textContent=r.lastMessage+' · '+r.writes+' 次已验证写入';}$('#control-events').innerHTML=s.events.slice().reverse().map(e=>`<p>${esc(new Date(e.at).toLocaleTimeString())} · ${esc(({armed:'开始自动控制','manual-takeover':'人工接管','write-requested':'请求写入','write-verified':'回读一致',fault:'中止'})[e.event]||e.event)} ${esc(e.message||(current.project.control?.rules||[]).find(r=>r.id===e.ruleId)?.name||e.ruleId||'')} ${e.value!==undefined?'→ '+esc(typeof e.value==='boolean'?Number(e.value):e.value):''}</p>`).join('')||'<p>暂无控制记录</p>';}catch(e){if(!closed)$('#control-reason').textContent=e.message;}if(schedule&&!closed)timer=setTimeout(poll,1000);}
  d.addEventListener('close',()=>{closed=true;clearTimeout(timer);d.classList.remove('control-dialog')},{once:true});list();poll();
 }catch(e){toast('无法打开控制面板：'+e.message)}
}
