import {waterKnowledge} from './industry-example.mjs';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function openKnowledgePanel({api,dialog,save,accept,toast}){
 try{await save();let current=await api('/agent/state'),preview=null;
 const d=dialog('行业知识库',`<p>维护可追溯的资料。来源由维护者提供，软件不会把它自动认证为行业标准。修改资料会增加版本，并停用引用旧版本的控制规则。</p><div class="knowledge-tools"><input id="knowledge-search" aria-label="搜索知识资料" placeholder="搜索标题、行业或正文"><button id="knowledge-add" class="primary">新增资料</button><button id="knowledge-import">导入 JSON</button><button id="knowledge-export">导出资料</button></div><input id="knowledge-file" type="file" accept="application/json,.json" hidden><div class="knowledge-tools"><button id="knowledge-mode">启用行业 AI 模式</button><button id="knowledge-seed">载入供水示例资料</button><span id="knowledge-mode-status"></span></div><div id="knowledge-list"></div><form id="knowledge-form" hidden></form><div id="knowledge-preview" aria-live="polite"></div><div class="dialog-actions"><button id="knowledge-apply" class="primary" disabled>应用资料修改</button></div>`);
 d.classList.add('knowledge-dialog');d.addEventListener('close',()=>d.classList.remove('knowledge-dialog'),{once:true});const $=s=>d.querySelector(s);
 function entries(){return current.project.knowledge||[]}
 function list(){const query=$('#knowledge-search').value.toLowerCase(),matched=entries().filter(e=>(e.title+' '+e.domain+' '+e.content).toLowerCase().includes(query));$('#knowledge-mode-status').textContent=current.project.system?.mode==='industry-ai'?'当前工程：行业 AI':'当前工程尚未启用行业 AI';$('#knowledge-mode').disabled=current.project.system?.mode==='industry-ai';$('#knowledge-list').innerHTML=matched.map(e=>`<article class="knowledge-card"><div><strong>${esc(e.title)}</strong><span>v${e.version} · ${esc(e.domain)}</span></div><p class="hint">来源：${esc(e.source)}</p><p class="hint">${e.validUntil?'有效至 '+esc(new Date(e.validUntil).toLocaleDateString())+(Date.parse(e.validUntil)<=Date.now()?' · 已过期':''):'未设置有效期，请定期复核'}</p><details><summary>查看正文</summary><p class="knowledge-content">${esc(e.content)}</p></details><div class="knowledge-tools"><button data-edit-entry="${esc(e.id)}">编辑资料</button><button data-remove-entry="${esc(e.id)}">删除资料</button></div></article>`).join('')||'<p class="hint">没有匹配的资料。可新增条目或导入 JSON。</p>';for(const b of d.querySelectorAll('[data-edit-entry]'))b.onclick=()=>form(entries().find(e=>e.id===b.dataset.editEntry));for(const b of d.querySelectorAll('[data-remove-entry]'))b.onclick=()=>plan([{op:'knowledge.delete',id:b.dataset.removeEntry}],'删除知识资料，检查受影响的规则');}
 function field(label,key,value,type='text'){return `<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${key==='validUntil'?'':'required'}></label>`}
 function form(e){const id=e?.id||'knowledge_'+crypto.randomUUID().replaceAll('-','').slice(0,12);$('#knowledge-form').hidden=false;$('#knowledge-form').innerHTML=`<h3>${e?'更新资料版本':'新增资料'}</h3><div class="knowledge-grid">${field('标题','title',e?.title||'')}${field('行业 / 适用领域','domain',e?.domain||'')}${field('来源说明 / 文件或网址','source',e?.source||'')}${field('新版本号','version',(e?.version||0)+1,'number')}${field('有效至（可选）','validUntil',e?.validUntil?.slice(0,10)||'','date')}</div><label>正文<textarea name="content" required maxlength="20000">${esc(e?.content||'')}</textarea></label><div class="knowledge-tools"><button type="submit" class="primary">检查资料修改</button><button type="button" id="knowledge-form-close">取消编辑</button></div>`;$('#knowledge-form-close').onclick=()=>{$('#knowledge-form').hidden=true};$('#knowledge-form').onsubmit=ev=>{ev.preventDefault();const data=new FormData(ev.currentTarget),entry={id,title:data.get('title'),domain:data.get('domain'),source:data.get('source'),version:Number(data.get('version')),content:data.get('content'),validUntil:data.get('validUntil')?new Date(data.get('validUntil')+'T23:59:59.999').toISOString():null};plan([{op:'knowledge.upsert',entry}],'更新知识资料及关联依据');};}
 async function plan(operations,summary){preview=null;$('#knowledge-apply').disabled=true;try{preview=await api('/agent/plans',{expectedRevision:current.revision,actor:'knowledge-panel',summary,operations});$('#knowledge-preview').innerHTML=`<h3>${esc(summary)}</h3><p>${preview.changes.length} 项对象变化</p><ul>${[...preview.impacts,...preview.diagnostics].map(i=>`<li>${esc(i.message)}</li>`).join('')}</ul>`;$('#knowledge-apply').disabled=preview.blocked;}catch(e){$('#knowledge-preview').textContent=e.message}}
 $('#knowledge-search').oninput=list;$('#knowledge-add').onclick=()=>form();$('#knowledge-mode').onclick=()=>plan([{op:'project.configure',mode:'industry-ai'}],'启用行业 AI 模式；保持人工接管');
 $('#knowledge-seed').onclick=()=>{const data=waterKnowledge().filter(e=>!entries().some(x=>x.id===e.id));if(!data.length){toast('供水示例资料已存在，不会覆盖现有版本');return;}plan(data.map(entry=>({op:'knowledge.upsert',entry})),'载入供水演示资料；这些资料不是行业标准');};
 $('#knowledge-import').onclick=()=>$('#knowledge-file').click();$('#knowledge-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1500000)throw Error('资料文件最多 1.5 MB');const data=JSON.parse(await file.text()),items=Array.isArray(data)?data.entries:null;if(!items?.length||items.length>100)throw Error('JSON 应包含 1–100 条资料数组，或 {entries:[…]}');await plan(items.map(entry=>({op:'knowledge.upsert',entry})),'导入知识资料，检查版本与关联影响');}catch(err){$('#knowledge-preview').textContent=err.message}finally{e.target.value=''}};
 $('#knowledge-export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'simplehmi-knowledge-v1',entries:entries()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='FlexHMI-知识资料.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('#knowledge-apply').onclick=async()=>{if(!preview)return;$('#knowledge-apply').disabled=true;try{await api(`/agent/plans/${preview.id}/apply`,{});await accept(await api('/project'));current=await api('/agent/state');preview=null;$('#knowledge-form').hidden=true;$('#knowledge-preview').textContent='资料已保存。';list();}catch(e){$('#knowledge-preview').textContent=e.message}};list();
 }catch(e){toast('无法打开知识库：'+e.message)}
}
export function assessmentMarkup(a){if(!a)return '';return `<section class="assessment-report"><h3>评估结论</h3><p>${esc(a.conclusion)}</p><p class="hint">观测于 ${esc(new Date(a.capturedAt).toLocaleString())} · 建议有效至 ${esc(new Date(a.expiresAt).toLocaleTimeString())}</p><h4>引用依据</h4>${a.citations.map(c=>`<article><strong>${esc(c.title)} · v${c.version}</strong><p class="hint">${esc(c.source)}</p><blockquote>${esc(c.excerpt)}</blockquote></article>`).join('')}<h4>应用前需仍满足</h4><ul>${a.conditions.map(c=>`<li>${esc(a.observed[c.tagId]?.name||c.tagId)}：${c.min} ～ ${c.max} ${esc(a.observed[c.tagId]?.unit||'')}（采样 ${esc(typeof a.observed[c.tagId]?.value==='boolean'?Number(a.observed[c.tagId].value):a.observed[c.tagId]?.value)}）</li>`).join('')}</ul></section>`}
